In [ ]:
from modelo import cargar_instancia, crear_modelo_convrp
import gurobipy as gp
from gurobipy import GRB
import pandas as pd
from IPython.display import display
import os

# Modelos

In [ ]:
def optimizar_modelo_base(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    
    print("¡Optimizando modelo base!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_relajado(datos):
    modelo = crear_modelo_convrp(datos)
    
    # Convierte las variables binarias a continuas
    modelo = modelo.relax()
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    
    print("¡Optimizando modelo relajado!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_cuts(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.Cuts = 0
    
    print("¡Optimizando modelo con cuts = 0!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_presolve(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.Presolve = 0
    
    print("¡Optimizando modelo con presolve = 0!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_mipfocus_1(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.MIPFocus = 1
    
    print("¡Optimizando modelo con MIPFocus = 1!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_mipfocus_3(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.MIPFocus = 3
    
    print("¡Optimizando modelo con MIPFocus = 3!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_heuristics(datos):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.Heuristics = 0
    
    print("¡Optimizando modelo con heuristics = 0!\n")
    modelo.optimize()
    return modelo

def optimizar_modelo_tuneado(datos, nombre_instancia):
    modelo = crear_modelo_convrp(datos)
    
    modelo.Params.Threads = 1
    modelo.Params.TimeLimit = 600
    modelo.Params.TuneTimeLimit = 3600
    
    print("¡Optimizando parametros!\n")
    modelo.tune()
    
    if modelo.TuneResultCount > 0:
        modelo.getTuneResult(0)
        os.makedirs("parametros", exist_ok=True)
        modelo.write(f"parametros/mejores_parametros_{nombre_instancia}.prm")
    
    print("¡Optimizando modelo con parametros tuneados!")
    modelo.optimize()
    return modelo

# Funciones para análisis de resultados

In [ ]:
def reporte_modelo(modelo, nombre_modelo, nombre_instancia):
    tiempo_ejecucion = modelo.Runtime
    
    if modelo.SolCount > 0:
        valor_objetivo = modelo.ObjVal
        gap_final = modelo.MIPGap
        
        print(f"\n¡Reporte {nombre_modelo} {nombre_instancia}!\n"
                  f"Tiempo de ejecución: {tiempo_ejecucion:.2f}\n"
                  f"Valor objetivo: {valor_objetivo}\n"
                  f"Gap final: {gap_final}\n")
    else:
        modelo.computeIIS()
        modelo.write("modelo_infactible.ilp")
        print("Archivo 'modelo_infactible.ilp' generado con éxito.")
        
    

def comparacion_baseline_relajado(baseline, relajado):
    if baseline.SolCount > 0 and relajado.SolCount > 0:
        brecha_integralidad = 100 * (baseline.ObjVal - relajado.ObjVal) / baseline.ObjVal
        print(f"Valor objetivo modelo baseline: {baseline.ObjVal:2f}\n"
            f"Valor objetivo modelo relajado: {relajado.ObjVal:2f}\n"
            f"Brecha de integralidad: {brecha_integralidad}%\n")
    else:
        print("No se puede calcular la brecha de integralidad puesto que nos e obtuvo una solucion factible en alguno de los modelos.\n")

def comparacion_modelos(modelos, nombres, instancia):
    data = {
            "Modelo": [],
            "Tiempo": [],
            "Valor Objetivo": [],
            "Gap Final": []
            }
    
    for i, m in enumerate(modelos):
        data["Modelo"].append(nombres[i])
        data["Tiempo"].append(m.Runtime)
        data["Valor Objetivo"].append(m.ObjVal)
        data["Gap Final"].append(m.MIPGap)
    
    print(f"=== Comparativa de modelos {instancia} ===\n")
    df = pd.DataFrame(data)
    display(df)
    
def analisis_sensibilidad_capacidad(modelo, nombre_instancia, tol=1e-6):
    if modelo.SolCount == 0:
        print(f"[{nombre_instancia}] No hay solución incumbente: no se puede fijar el modelo.")
        return None, None

    fm = modelo.fixed()          # MIP -> LP con enteras fijas en la incumbente
    fm.Params.Presolve = 0       # evita que se eliminen filas con solo variables fijas
    fm.Params.Method = 1         # simplex dual
    fm.Params.Threads = 1
    fm.Params.OutputFlag = 0
    fm.optimize()

    if fm.Status != GRB.OPTIMAL:
        print(f"[{nombre_instancia}] El modelo fijado no es óptimo (estado {fm.Status}).")
        return None, fm

    filas = []
    for c in fm.getConstrs():
        # Criterio 1: Nombre explícito que empiece con "Capacidad"
        es_capacidad = c.ConstrName.lower().startswith("capacidad")
        
        # Criterio 2: Restricción de tipo <= compuesta por variables Z
        if not es_capacidad and c.Sense == '<':
            row = fm.getRow(c)
            if row.size() > 0:
                es_capacidad = all(row.getVar(i).VarName.startswith("Z_") for i in range(row.size()))

        if es_capacidad:
            carga = c.RHS - c.Slack
            nombre_mostrar = c.ConstrName if c.ConstrName.lower().startswith("capacidad") else f"Capacidad ({c.ConstrName})"
            filas.append({
                "Restricción": nombre_mostrar,
                "Q (RHS)": c.RHS,
                "Carga": carga,
                "Holgura": c.Slack,
                "Activa": c.Slack < tol,
                "Precio sombra (Pi)": c.Pi,
                "SARHSLow": c.SARHSLow,
                "SARHSUp": c.SARHSUp,
            })

    df = pd.DataFrame(filas)

    # Validación de seguridad si no se encuentran filas
    if df.empty:
        print(f"=== Sensibilidad de Q, instancia {nombre_instancia} ===")
        print(f"[{nombre_instancia}] No se identificaron restricciones de capacidad en el modelo.")
        return None, fm

    print(f"=== Sensibilidad de Q, instancia {nombre_instancia} ===")
    print(f"Objetivo MIP: {modelo.ObjVal:.4f} | Objetivo LP fijado: {fm.ObjVal:.4f}")
    print(f"Restricciones de capacidad: {len(df)} | activas: {int(df['Activa'].sum())}")
    print(f"Carga máxima observada: {df['Carga'].max():.2f} (Q = {df['Q (RHS)'].iloc[0]:.2f})")
    print(f"Filas con precio sombra distinto de 0: {(df['Precio sombra (Pi)'].abs() > tol).sum()}")
    display(df.sort_values("Carga", ascending=False).head(15))
    
    return df, fm

In [4]:
datos_1 = cargar_instancia("instancias/C108.json")
datos_2 = cargar_instancia("instancias/R108.json")

## Modelo Base

In [5]:
modelo_base_I1 = optimizar_modelo_base(datos_1)
reporte_modelo(modelo_base_I1, "modelo base", "I1")

Set parameter Username
Set parameter LicenseID to value 2875196
Academic license - for non-commercial use only - expires 2027-10-15
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
¡Optimizando modelo base!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 783 rows and 397 columns
Presolve time: 0.01s
Presolved: 645 rows, 890 columns, 3102 nonzeros
Variable types: 32 continuous, 858 integer (858 binary)

Root relaxation: objective 2.239768e+02, 325 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0   98          -  223.97683      -     -    0s
H    0     0                     486.7936321  223.97683  54.0%     -    0s
     0     0  242.92686    0  142  486.79363  242.92686  50.1%     -    0s
H    0     0                     421.4118364  243.35134  42.3%     -    0s
     0     0  298.86762    0  111  421.41184  298.86762  29.1%     -    0s
     0     0  299.90768    0  117  421.41184  299.90768  28.8%     -    0s
     0     0  301.05408    0  108  421.41184  301.05408  28.6%     -    0s
     0     0  301.42009    0  108  421.41184  301.42009  28.5%     -    0s
     0     0  301.46380    0  103  421.41184  301.46380  28.5%     -    0s
     0     0  304.11982    0  116  421.41184  304.11982  27.8%     -    0s
     0     0  308.25384    0   55  421.41184  308.25384  26.9%     -    0s
     0     0  308.82915    0   40  421.41184  308.82915  26.7%     -    0s
     0     0  332.29823    0   50  421.41184  332.29823  21.1%     -    0s
H    0     0                     418.2132300  332.29823  20.5%     -    0s
     0     0  333.20689    0   49  418.21323  333.20689  20.3%     -    0s
     0     0  333.49819    0  122  418.21323  333.49819  20.3%     -    0s
     0     0  333.55986    0  116  418.21323  333.55986  20.2%     -    0s
     0     0  334.04270    0  156  418.21323  334.04270  20.1%     -    0s
     0     0  334.06661    0  152  418.21323  334.06661  20.1%     -    0s
     0     0  347.56029    0  136  418.21323  347.56029  16.9%     -    0s
H    0     0                     417.8550364  347.62554  16.8%     -    0s
     0     0  347.94185    0  138  417.85504  347.94185  16.7%     -    0s
     0     0  349.73439    0  138  417.85504  349.73439  16.3%     -    0s
     0     0  349.74698    0  138  417.85504  349.74698  16.3%     -    0s
     0     0  353.44526    0  138  417.85504  353.44526  15.4%     -    0s
     0     0  354.99840    0  147  417.85504  354.99840  15.0%     -    0s
     0     0  355.57019    0  177  417.85504  355.57019  14.9%     -    0s
     0     0  355.59945    0  152  417.85504  355.59945  14.9%     -    0s
     0     0  358.07713    0  148  417.85504  358.07713  14.3%     -    0s
H    0     0                     416.1362581  358.14915  13.9%     -    0s
     0     0  358.14915    0  214  416.13626  358.14915  13.9%     -    0s
     0     0  358.98539    0  214  416.13626  358.98539  13.7%     -    0s
     0     0  358.99193    0  210  416.13626  358.99193  13.7%     -    0s
     0     0  359.02279    0  146  416.13626  359.02279  13.7%     -    0s
     0     0  359.14076    0  204  416.13626  359.14076  13.7%     -    0s
     0     0  359.14130    0  206  416.13626  359.14130  13.7%     -    0s
     0     0  359.18947    0  148  416.13626  359.18947  13.7%     -    0s
     0     0  359.21781    0  146  416.13626  359.21781  13.7%     -    0s
     0     0  359.47518    0  217  416.13626  359.47518  13.6%     -    0s
     0     0  359.54866    0  217  416.13626  359.54866  13.6%     -    0s
     0     0  359.54866    0  217  416.13626  359.54866  13.6%     -    0s
     0     2  359.60133    0  217  416.13626  359.60133  13.6%     -    0s
H  309   126                     414.5346037  366.90537  11.5%  23.6    0s
* 1380    67              15     411.7982271  397.38531  3.50%  24.6    2s

Cutting planes:
  Learned: 69
  Gomory: 2
  Cover: 71
  Implied bound: 60
  Clique: 36
  MIR: 36
  Inf proof: 6
  Zero half: 9
  RLT: 13
  Relax-and-lift: 38
  BQP: 11

Explored 1492 nodes (37818 simplex iterations) in 2.46 seconds (1.82 work units)
Thread count was 1 (of 16 available processors)

Solution count 7: 411.798 414.535 416.136 ... 486.794

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo base I1!
Tiempo de ejecución: 2.47
Valor objetivo: 411.7982271426954
Gap final: 0.0

In [6]:
modelo_base_I2 = optimizar_modelo_base(datos_2)
reporte_modelo(modelo_base_I2, "modelo base", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
¡Optimizando modelo base!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.03s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)

Root relaxation: objective 5.394012e+02, 540 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  103          -  539.40121      -     -    0s
     0     0  547.80610    0  173          -  547.80610      -     -    0s
     0     0  587.57156    0  161          -  587.57156      -     -    0s
     0     0  591.01636    0   96          -  591.01636      -     -    0s
     0     0  591.24772    0   82          -  591.24772      -     -    0s
     0     0  598.99590    0  112          -  598.99590      -     -    0s
     0     0  600.76258    0  159          -  600.76258      -     -    0s
     0     0  600.79084    0  179          -  600.79084      -     -    0s
     0     0  600.80480    0  198          -  600.80480      -     -    0s
     0     0  608.78711    0  234          -  608.78711      -     -    0s
     0     0  609.22028    0  156          -  609.22028      -     -    0s
     0     0  609.30100    0  217          -  609.30100      -     -    0s
     0     0  609.36353    0  206          -  609.36353      -     -    0s
     0     0  609.37391    0  173          -  609.37391      -     -    0s
     0     0  611.18715    0  226          -  611.18715      -     -    0s
     0     0  611.72083    0  196          -  611.72083      -     -    0s
     0     0  611.86859    0  221          -  611.86859      -     -    0s
     0     0  611.94839    0  170          -  611.94839      -     -    0s
     0     0  611.94839    0  141          -  611.94839      -     -    0s
     0     0  612.49640    0  175          -  612.49640      -     -    0s
     0     0  612.50680    0  180          -  612.50680      -     -    0s
     0     0  612.50680    0  183          -  612.50680      -     -    0s
     0     0  612.69840    0  183          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  140          -  612.69840      -     -    0s
     0     2  612.88549    0  138          -  612.88549      -     -    0s
H  637   451                     936.5462785  635.33787  32.2%  20.5    3s
H  637   428                     925.4757949  635.33787  31.4%  20.5    3s
   647   435  665.39652   15  284  925.47579  636.60671  31.2%  20.1    5s
H  648   414                     844.5315761  636.60671  24.6%  26.5    5s
H  648   392                     841.0582862  636.60671  24.3%  26.5    5s
H  649   372                     840.7017084  636.60671  24.3%  26.7    5s
H  649   353                     840.1164889  636.60671  24.2%  26.7    5s
H  649   334                     839.3136417  636.60671  24.2%  26.7    5s
H  756   363                     830.1588823  646.32366  22.1%  30.7    6s
H  756   346                     827.8976697  646.32366  21.9%  30.7    6s
H 1138   403                     794.0304202  656.75627  17.3%  39.5    8s
  1338   471 infeasible   23       794.03042  659.35675  17.0%  40.3   10s
H 1848   670                     793.6310751  666.22962  16.1%  42.5   12s
H 1848   640                     782.3070372  666.22962  14.8%  42.5   12s
H 2048   745                     780.4791053  668.88098  14.3%  43.1   13s
  2478   963  683.38590   21  113  780.47911  673.76765  13.7%  42.2   15s
H 3050  1242                     779.1096739  677.57178  13.0%  41.5   16s
H 3050  1238                     778.4295960  677.57178  13.0%  41.5   16s
H 3050  1227                     775.2900138  677.57178  12.6%  41.5   16s
  4029  1675 infeasible   31       775.29001  683.11156  11.9%  40.4   20s
  5689  2316  716.39163   27  108  775.29001  689.30538  11.1%  38.2   25s
  7372  2950  734.09467   23   98  775.29001  693.83542  10.5%  36.8   30s
  9134  3603  728.51160   25  117  775.29001  698.23221  9.94%  35.6   35s
 10203  3981  752.46230   34  140  775.29001  700.48557  9.65%  34.8   46s
 10225  3996  706.21631   35  283  775.29001  700.48557  9.65%  34.7   50s
 10243  4008  722.21929   34  319  775.29001  700.48557  9.65%  34.7   55s
 10260  4019  747.43074   36  310  775.29001  700.48557  9.65%  34.6   60s
 10277  4030  712.68582   26  327  775.29001  700.48557  9.65%  34.6   65s
 10308  4051  740.57492   32  336  775.29001  700.48557  9.65%  34.5   70s
 10503  4122  700.48557   37   93  775.29001  700.48557  9.65%  36.2   75s
 10994  4201  700.48557   32  125  775.29001  700.48557  9.65%  37.1   80s
 11805  4280  718.90262   36   80  775.29001  700.48557  9.65%  37.3   85s
 12855  4402  731.60332   34  104  775.29001  700.48557  9.65%  37.3   90s
 14734  4511  771.45115   46   63  775.29001  704.07549  9.19%  36.6   95s
 16170  4481  746.10869   37  144  775.29001  709.47768  8.49%  36.0  100s
 17601  4436  761.10526   42   67  775.29001  713.62817  7.95%  35.6  105s
 19632  4317  744.09166   37  108  775.29001  716.95721  7.52%  34.8  110s
 21825  4202  768.96531   43   85  775.29001  720.65629  7.05%  34.0  115s
 23931  4438  738.94784   40   74  775.29001  723.55235  6.67%  33.3  120s
 25835  4784  755.92899   40   83  775.29001  726.11937  6.34%  33.0  125s
 27647  5135  769.96767   36   89  775.29001  728.11607  6.08%  32.7  130s
 29802  5451  745.52867   38   47  775.29001  730.31641  5.80%  32.2  135s
 31911  5694  771.68537   44   37  775.29001  732.35041  5.54%  31.9  140s
 34125  5894  750.90810   43   41  775.29001  734.54934  5.25%  31.5  145s
 36804  6078  747.86464   39  118  775.29001  736.56548  4.99%  31.1  150s
 39244  6216  758.66407   41   79  775.29001  738.55172  4.74%  30.8  155s
 41311  6314  773.19590   43   48  775.29001  739.96286  4.56%  30.5  160s
*42739  6080              54     769.2419314  741.06847  3.66%  30.3  162s
 43235  6039     cutoff   44       769.24193  741.51256  3.60%  30.2  165s
 45208  5817     cutoff   44       769.24193  743.53717  3.34%  30.0  170s
 47326  5584  756.68053   44   71  769.24193  745.65521  3.07%  29.8  175s
 49342  5213     cutoff   47       769.24193  747.71115  2.80%  29.5  180s
 51638  4682  756.75292   46   88  769.24193  750.09773  2.49%  29.3  185s
 53954  4027  763.87402   43   59  769.24193  752.53485  2.17%  29.0  190s
 56472  2967  766.96052   41   54  769.24193  755.83443  1.74%  28.8  195s
 59297  1176     cutoff   46       769.24193  761.60043  0.99%  28.3  200s

Cutting planes:
  Learned: 24
  Gomory: 2
  Cover: 263
  Implied bound: 126
  Projected implied bound: 22
  Clique: 50
  MIR: 41
  StrongCG: 5
  Flow cover: 179
  GUB cover: 12
  Inf proof: 18
  Zero half: 109
  RLT: 7
  Relax-and-lift: 15
  BQP: 5

Explored 60628 nodes (1694512 simplex iterations) in 201.68 seconds (134.50 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 769.242 769.242 775.29 ... 827.898

Optimal solution found (tolerance 1.00e-04)
Best objective 7.692419314269e+02, best bound 7.691732573051e+02, gap 0.0089%

¡Reporte modelo base I2!
Tiempo de ejecución: 201.69
Valor objetivo: 769.2419314269123
Gap final: 8.927506292814019e-05

## Modelo Relajado

In [7]:
modelo_relajado_I1 = optimizar_modelo_relajado(datos_1)

# Comparacion del baseline con el relajado
comparacion_baseline_relajado(modelo_base_I1, modelo_relajado_I1)

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
¡Optimizando modelo relajado!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xbdbb084e
Model has 1188 linear objective coefficients
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 405 rows and 27 columns
Presolve time: 0.02s
Presolved: 1023 rows, 1260 columns, 5061 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   3.150000e+01   0.000000e+00      0s
     161    1.2514096e+02   0.000000e+00   0.000000e+00      0s

Use crossover to convert LP symmetric solution to basic solution...
Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 0s

      30 PPushes remaining with PInf 0.0000000e+00                 0s
       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 1.1466455e+00      0s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
     312    1.2514096e+02   0.000000e+00   1.146646e+00      0s
Crossover time: 0.02 seconds (0.00 work units)
     325    1.2514096e+02   0.000000e+00   0.000000e+00      0s

Solved in 325 iterations and 0.06 seconds (0.01 work units)
Optimal objective  1.251409648e+02
Valor objetivo modelo baseline: 411.798227
Valor objetivo modelo relajado: 125.140965
Brecha de integralidad: 69.61109674856814%

In [8]:
modelo_relajado_I2 = optimizar_modelo_relajado(datos_2)

# Comparacion del baseline con el relajado
comparacion_baseline_relajado(modelo_base_I2, modelo_relajado_I2)

Set parameter Threads to value 1

Set parameter TimeLimit to value 600
¡Optimizando modelo relajado!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0x811a7184
Model has 1260 linear objective coefficients
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 192 rows and 27 columns
Presolve time: 0.01s
Presolved: 1314 rows, 1333 columns, 6029 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   3.300000e+01   0.000000e+00      0s
     206    5.2091919e+02   0.000000e+00   0.000000e+00      0s

Use crossover to convert LP symmetric solution to basic solution...
Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 0s

      17 PPushes remaining with PInf 0.0000000e+00                 0s
       0 PPushes remaining with PInf 0.0000000e+00                 0s

  Push phase complete: Pinf 0.0000000e+00, Dinf 4.3355780e-01      0s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
     384    5.2091919e+02   0.000000e+00   4.335578e-01      0s
Crossover time: 0.02 seconds (0.00 work units)
     391    5.2091919e+02   0.000000e+00   0.000000e+00      0s

Solved in 391 iterations and 0.06 seconds (0.01 work units)
Optimal objective  5.209191942e+02
Valor objetivo modelo baseline: 769.241931
Valor objetivo modelo relajado: 520.919194
Brecha de integralidad: 32.281487411800136%

## Prueba de configuración de modelos
### Modelo Cuts = 0

In [9]:
# Optimización del modelo con configuración 1 con ambas instancias
modelo_cuts_I1 = optimizar_modelo_cuts(datos_1)
reporte_modelo(modelo_cuts_I1, "modelo Cuts = 0", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Cuts to value 0
¡Optimizando modelo con cuts = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Cuts  0
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 783 rows and 397 columns
Presolve time: 0.02s
Presolved: 645 rows, 890 columns, 3102 nonzeros
Variable types: 32 continuous, 858 integer (858 binary)

Root relaxation: objective 2.239768e+02, 325 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0   98          -  223.97683      -     -    0s
H    0     0                     486.7936321  223.97683  54.0%     -    0s
     0     0  239.67499    0  118  486.79363  239.67499  50.8%     -    0s
     0     0  239.67499    0  111  486.79363  239.67499  50.8%     -    0s
H    0     0                     486.3960090  251.64521  48.3%     -    0s
H    0     0                     485.0675738  251.64521  48.1%     -    0s
     0     2  251.64521    0  111  485.06757  251.64521  48.1%     -    0s
H    5     5                     483.4659195  266.14844  44.9%  16.4    0s
H   31    19                     480.5015447  267.97201  44.2%  17.4    0s
H   31    19                     480.1433510  267.97201  44.2%  17.4    0s
*   52    37              18     420.2664843  267.97201  36.2%  20.0    0s
H   60    34                     417.3021095  274.19877  34.3%  22.9    0s
H  136    91                     416.9439159  293.82192  29.5%  23.1    0s
*  331   190              18     416.8247927  308.58902  26.0%  23.1    0s
*  409   221              15     416.3351748  309.66026  25.6%  22.8    0s
H  494   250                     415.0067397  310.99253  25.1%  23.0    0s
H  810   324                     414.5346037  316.07140  23.8%  22.2    1s
* 1338   340              26     413.5952392  327.72843  20.8%  23.6    2s
H 1538   312                     413.4133733  341.57148  17.4%  23.7    3s
* 1564   289              29     411.7982271  346.67264  15.8%  23.7    3s

Explored 2211 nodes (49024 simplex iterations) in 4.46 seconds (2.07 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 411.798 413.413 413.595 ... 420.266

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo Cuts = 0 I1!
Tiempo de ejecución: 4.47
Valor objetivo: 411.79822714269534
Gap final: 0.0

In [10]:
modelo_cuts_I2 = optimizar_modelo_cuts(datos_2)
reporte_modelo(modelo_cuts_I2, "modelo Cuts = 0", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Cuts to value 0
¡Optimizando modelo con cuts = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Cuts  0
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.06s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)

Root relaxation: objective 5.394012e+02, 540 iterations, 0.02 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  103          -  539.40121      -     -    0s
     0     0  544.17444    0  133          -  544.17444      -     -    0s
     0     0  544.17444    0   96          -  544.17444      -     -    0s
     0     2  551.83059    0   96          -  551.83059      -     -    0s
H  409   341                     949.1971941  560.02768  41.0%  16.5    1s
H  501   385                     944.6922916  562.34976  40.5%  15.7    1s
H  536   412                     934.5636520  562.44563  39.8%  15.7    1s
H  570   433                     923.4931683  562.44563  39.1%  15.8    1s
H  609   438                     866.0471808  562.71546  35.0%  16.8    1s
H  649   440                     829.5092875  562.71546  32.2%  17.7    2s
H  650   420                     828.0728424  562.71546  32.0%  17.7    2s
H  650   400                     812.6022481  562.71546  30.8%  17.7    2s
H  650   381                     807.9553640  562.71546  30.4%  17.7    2s
H  650   364                     799.8538097  562.71546  29.6%  17.7    2s
H  650   347                     792.6657520  562.71546  29.0%  17.7    2s
H  688   343                     788.5352661  562.71546  28.6%  18.7    2s
H  707   337                     784.2987654  562.71546  28.3%  19.7    2s
H  707   323                     780.4791053  562.71546  27.9%  19.7    2s
  1091   416  740.33157   49   78  780.47911  578.17839  25.9%  25.9    5s
  2210   879  629.93027   24   96  780.47911  599.48322  23.2%  28.3   10s
H 2958  1217                     777.5849922  605.74410  22.1%  28.2   12s
  3495  1452  673.64737   34   90  777.58499  609.08112  21.7%  28.6   15s
  5182  2239  642.42895   30   88  777.58499  616.55490  20.7%  28.0   20s
H 6624  2934                     775.2900138  620.64375  19.9%  27.4   24s
  6904  3077  638.96416   26  119  775.29001  621.64624  19.8%  27.4   25s
  8866  3947  738.87024   49   84  775.29001  627.13704  19.1%  27.6   30s
H 9094  4023                     769.2419314  627.51525  18.4%  27.6   30s
 10523  4602  646.64847   30  114  769.24193  630.39916  18.0%  27.5   35s
 12590  5421  756.34059   30   73  769.24193  634.06925  17.6%  27.7   40s
 14604  6314  657.37612   34  104  769.24193  637.07135  17.2%  27.3   45s
 16579  7149  754.02214   31   68  769.24193  639.80663  16.8%  27.2   50s
 19005  8069 infeasible   37       769.24193  642.65444  16.5%  27.0   55s
 21456  8987  672.16196   40  107  769.24193  645.05398  16.1%  26.7   60s
 23653  9694  732.29061   31   62  769.24193  647.28703  15.9%  26.8   65s
 26238 10581  667.73341   36  105  769.24193  649.09355  15.6%  26.6   70s
 28981 11503  760.27034   37  102  769.24193  651.14647  15.4%  26.3   75s
 31456 12378  752.45210   38  101  769.24193  652.68411  15.2%  26.1   80s
 34179 13269  705.46341   33   89  769.24193  654.42269  14.9%  26.0   85s
 36653 14006  753.72445   38   79  769.24193  656.28641  14.7%  25.8   90s
 39274 14794  680.68843   27   91  769.24193  657.82773  14.5%  25.6   95s
 41913 15624  689.12910   34   70  769.24193  659.56318  14.3%  25.3  100s
 44483 16319  679.69693   33   73  769.24193  661.27052  14.0%  25.2  105s
 47028 16953 infeasible   34       769.24193  662.59359  13.9%  25.1  110s
 49623 17769  702.06449   40   87  769.24193  663.99621  13.7%  24.9  115s
 51799 18417  684.30708   36   72  769.24193  665.12113  13.5%  24.8  120s
 54287 19070  739.56676   31  105  769.24193  666.50194  13.4%  24.7  125s
 56968 19802  754.21374   33   64  769.24193  667.82484  13.2%  24.5  130s
 59672 20504  737.49541   37  105  769.24193  669.12046  13.0%  24.4  135s
 62227 21153  690.68784   27  104  769.24193  670.17396  12.9%  24.3  140s
 64998 21874  727.92913   38   37  769.24193  671.41287  12.7%  24.2  145s
 67650 22556  708.28931   35   65  769.24193  672.29677  12.6%  24.1  150s
 70415 23207  684.18032   37   74  769.24193  673.16288  12.5%  24.0  155s
 73305 23866  762.46334   34   51  769.24193  674.31921  12.3%  23.9  160s
 76266 24563  733.51120   46  112  769.24193  675.31738  12.2%  23.8  165s
 79369 25247  720.05181   34   61  769.24193  676.31230  12.1%  23.6  170s
 82556 26069  680.96401   39   99  769.24193  677.21995  12.0%  23.5  175s
 85481 26725  732.88885   35   77  769.24193  678.19186  11.8%  23.3  180s
 88536 27424  689.64623   34  117  769.24193  679.07838  11.7%  23.2  185s
 91948 28261  691.63728   30  144  769.24193  679.95134  11.6%  23.0  190s
 95008 28945  702.82943   34   72  769.24193  680.80962  11.5%  22.9  195s
 97899 29644  756.99078   44   31  769.24193  681.64434  11.4%  22.8  200s
 101127 30443  755.88038   56   93  769.24193  682.44499  11.3%  22.7  205s
 104303 31127  718.36871   39   98  769.24193  683.26797  11.2%  22.6  210s
 107793 31930  686.79661   31   66  769.24193  684.13505  11.1%  22.5  215s
 111317 32715  734.17192   44   98  769.24193  684.94726  11.0%  22.4  220s
 114672 33448  762.94940   46   42  769.24193  685.74723  10.9%  22.2  225s
 118256 34209  745.17096   43   65  769.24193  686.56914  10.7%  22.1  230s
 121499 34853  749.78617   37   50  769.24193  687.21802  10.7%  22.1  235s
 124193 35426  762.57484   44   46  769.24193  687.76262  10.6%  22.0  240s
 127247 35909  726.19466   35   77  769.24193  688.48190  10.5%  21.9  245s
 130779 36634  726.57590   39   75  769.24193  689.30852  10.4%  21.8  250s
 134317 37336  728.09915   46   50  769.24193  690.00623  10.3%  21.7  255s
 137808 38068  744.84932   46   87  769.24193  690.64683  10.2%  21.6  260s
 141445 38773  744.27162   44  111  769.24193  691.35670  10.1%  21.5  265s
 144924 39389  725.79678   38   48  769.24193  692.02706  10.0%  21.5  270s
 148419 40020  707.72562   34   62  769.24193  692.62268  10.0%  21.4  275s
 152295 40703  760.34016   37   69  769.24193  693.27260  9.88%  21.3  280s
 155258 41229  698.64308   41   75  769.24193  693.71701  9.82%  21.2  285s
 158440 41829  720.12969   35   49  769.24193  694.25840  9.75%  21.1  290s
 161362 42405  709.61592   33   50  769.24193  694.75114  9.68%  21.1  295s
 164780 42992  754.39292   37   71  769.24193  695.25915  9.62%  21.0  300s
 168278 43611  713.86904   42   83  769.24193  695.78816  9.55%  20.9  305s
 171618 44236  711.81542   28  124  769.24193  696.28818  9.48%  20.8  310s
 174477 44790  734.72970   45   91  769.24193  696.68364  9.43%  20.8  315s
 177545 45335  740.97610   39  114  769.24193  697.09962  9.38%  20.7  320s
 180758 45880  712.22988   36   63  769.24193  697.56157  9.32%  20.7  325s
 183650 46371 infeasible   43       769.24193  697.97464  9.26%  20.6  330s
 187297 46967  741.06647   36   67  769.24193  698.49404  9.20%  20.5  335s
 190634 47467  735.90405   32   57  769.24193  698.98346  9.13%  20.5  340s
 193864 47987  743.37653   36   92  769.24193  699.42085  9.08%  20.4  345s
 197211 48452  714.28824   35   68  769.24193  699.89807  9.01%  20.4  350s
 200510 48948  703.96887   35   75  769.24193  700.35833  8.95%  20.4  355s
 203965 49339  731.98310   39   49  769.24193  700.84634  8.89%  20.3  360s
 207099 49753  753.75913   45   71  769.24193  701.19270  8.85%  20.3  365s
 209907 50112  744.93752   39   62  769.24193  701.55392  8.80%  20.2  370s
 213298 50506  749.95715   37   59  769.24193  701.98562  8.74%  20.2  375s
 216500 50862  717.95404   35   76  769.24193  702.39189  8.69%  20.2  380s
 219404 51171  723.63027   43   55  769.24193  702.73456  8.65%  20.2  385s
 222875 51563  704.78881   34   52  769.24193  703.14175  8.59%  20.1  390s
 225824 51848  721.13241   38   45  769.24193  703.48686  8.55%  20.1  395s
 229267 52204  751.59217   39   83  769.24193  703.84037  8.50%  20.0  400s
 232855 52643     cutoff   40       769.24193  704.26489  8.45%  20.0  405s
 236602 53084  752.56829   41   88  769.24193  704.67226  8.39%  19.9  410s
 240262 53471  765.12405   42   56  769.24193  705.06942  8.34%  19.9  415s
 243870 53864  763.07532   38   47  769.24193  705.47903  8.29%  19.8  420s
 247566 54183  739.48728   34   46  769.24193  705.89863  8.23%  19.8  425s
 250591 54476 infeasible   46       769.24193  706.27132  8.19%  19.7  430s
 253895 54790  711.38062   32  106  769.24193  706.64453  8.14%  19.7  435s
 257117 55049  752.16870   39   77  769.24193  707.00557  8.09%  19.7  440s
 260878 55363  763.21937   45   59  769.24193  707.42527  8.04%  19.6  445s
 265008 55778  710.95901   41   78  769.24193  707.81027  7.99%  19.6  450s
 268831 56101  718.52123   34   72  769.24193  708.20224  7.94%  19.5  455s
 272473 56385  743.58459   44   90  769.24193  708.56144  7.89%  19.5  460s
 276587 56742  727.83149   35   54  769.24193  708.97146  7.84%  19.4  465s
 280761 57085  725.04853   35   66  769.24193  709.33534  7.79%  19.4  470s
 284497 57384  750.81826   43   68  769.24193  709.69204  7.74%  19.3  475s
 287945 57638 infeasible   40       769.24193  710.02355  7.70%  19.3  480s
 291896 57881 infeasible   41       769.24193  710.37063  7.65%  19.2  485s
 295714 58108  741.00238   37   66  769.24193  710.72520  7.61%  19.2  490s
 299537 58397  746.35826   37   25  769.24193  711.06120  7.56%  19.2  495s
 303222 58638  730.68593   38   39  769.24193  711.36147  7.52%  19.1  500s
 307235 58925  718.05034   35   89  769.24193  711.72255  7.48%  19.1  505s
 311201 59169 infeasible   36       769.24193  712.07412  7.43%  19.0  510s
 315560 59465  727.54845   36   78  769.24193  712.46730  7.38%  19.0  515s
 319594 59716  720.54170   41   88  769.24193  712.81663  7.34%  18.9  520s
 323772 59934  763.12222   55   14  769.24193  713.19055  7.29%  18.9  525s
 328166 60091  731.74494   43   69  769.24193  713.58352  7.24%  18.8  530s
 332362 60307  760.00706   34   33  769.24193  713.94949  7.19%  18.8  535s
 336681 60531 infeasible   43       769.24193  714.32412  7.14%  18.7  540s
 340282 60679 infeasible   38       769.24193  714.60585  7.10%  18.7  545s
 344255 60886  730.01854   38   65  769.24193  714.92929  7.06%  18.7  550s
 348093 61093  732.80896   42   35  769.24193  715.24056  7.02%  18.6  555s
 352169 61317     cutoff   42       769.24193  715.54131  6.98%  18.6  560s
 356446 61532  762.72120   40   95  769.24193  715.88171  6.94%  18.5  565s
 360917 61699  758.19478   40   48  769.24193  716.22742  6.89%  18.5  570s
 365278 61867  760.74492   36   40  769.24193  716.56780  6.85%  18.5  575s
 369297 62102 infeasible   50       769.24193  716.86294  6.81%  18.4  580s
 373561 62200  764.82276   36   82  769.24193  717.19050  6.77%  18.4  585s
 377459 62289  734.67126   47   79  769.24193  717.47266  6.73%  18.3  590s
 381846 62452  745.27804   36   88  769.24193  717.78862  6.69%  18.3  595s

Explored 386349 nodes (7056203 simplex iterations) in 600.00 seconds (333.56 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 769.242 775.29 777.585 ... 812.602

Time limit reached
Best objective 7.692419314269e+02, best bound 7.181430180113e+02, gap 6.6428%

¡Reporte modelo Cuts = 0 I2!
Tiempo de ejecución: 600.01
Valor objetivo: 769.2419314269123
Gap final: 0.0664276235186793

### Modelo Presolve = 0

In [11]:
# Optimización del modelo con configuración 2 con ambas instancias
modelo_presolve_I1 = optimizar_modelo_presolve(datos_1)
reporte_modelo(modelo_presolve_I1, "modelo Presolve = 0", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Presolve to value 0
¡Optimizando modelo con presolve = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Presolve  0
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Variable types: 45 continuous, 1242 integer (1242 binary)
Found heuristic solution: objective 741.0587894

Root relaxation: objective 2.239768e+02, 341 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0  100  741.05879  223.97683  69.8%     -    0s
     0     0  230.17408    0  203  741.05879  230.17408  68.9%     -    0s
H    0     0                     688.4999612  230.17862  66.6%     -    0s
H    0     0                     684.9354252  230.17862  66.4%     -    0s
     0     0  304.69676    0  182  684.93543  304.69676  55.5%     -    0s
     0     0  305.20643    0  113  684.93543  305.20643  55.4%     -    0s
     0     0  310.86990    0  110  684.93543  310.86990  54.6%     -    0s
H    0     0                     679.7946150  310.91081  54.3%     -    0s
     0     0  310.94852    0  108  679.79461  310.94852  54.3%     -    0s
     0     0  310.94852    0  108  679.79461  310.94852  54.3%     -    0s
     0     0  318.67636    0  108  679.79461  318.67636  53.1%     -    0s
     0     0  318.67636    0  108  679.79461  318.67636  53.1%     -    0s
     0     0  319.61213    0  106  679.79461  319.61213  53.0%     -    0s
     0     0  322.42240    0  112  679.79461  322.42240  52.6%     -    0s
     0     0  322.42240    0  112  679.79461  322.42240  52.6%     -    0s
     0     0  331.23874    0  180  679.79461  331.23874  51.3%     -    0s
     0     0  332.23193    0  173  679.79461  332.23193  51.1%     -    0s
     0     0  332.75412    0  176  679.79461  332.75412  51.1%     -    0s
     0     0  339.88875    0  123  679.79461  339.88875  50.0%     -    0s
H    0     0                     646.2685192  340.04635  47.4%     -    0s
     0     0  342.96165    0  126  646.26852  342.96165  46.9%     -    0s
     0     0  342.96165    0  126  646.26852  342.96165  46.9%     -    0s
     0     0  346.87576    0   39  646.26852  346.87576  46.3%     -    0s
H    0     0                     474.9831478  346.87723  27.0%     -    0s
H    0     0                     473.4635142  346.87723  26.7%     -    0s
     0     0  349.94688    0  129  473.46351  349.94688  26.1%     -    0s
     0     0  349.94688    0  129  473.46351  349.94688  26.1%     -    0s
     0     0  355.32854    0  174  473.46351  355.32854  25.0%     -    0s
H    0     0                     467.6041432  355.32854  24.0%     -    0s
     0     0  355.32854    0  116  467.60414  355.32854  24.0%     -    0s
     0     0  355.33011    0  170  467.60414  355.33011  24.0%     -    0s
     0     0  355.55340    0  170  467.60414  355.55340  24.0%     -    0s
     0     0  355.55340    0  173  467.60414  355.55340  24.0%     -    0s
     0     0  355.55340    0  173  467.60414  355.55340  24.0%     -    0s
     0     0  355.55340    0  173  467.60414  355.55340  24.0%     -    0s
     0     2  355.57628    0  173  467.60414  355.57628  24.0%     -    0s
H   18    16                     463.7024790  355.57628  23.3%  29.6    0s
H   21    17                     449.8050360  355.57628  20.9%  26.6    0s
H   53    38                     441.8117883  355.57628  19.5%  32.0    0s
*  155   101              22     435.1946692  356.92971  18.0%  24.0    1s
H  301   169                     434.1318318  358.15744  17.5%  23.0    1s
H  579   312                     427.2599756  359.64884  15.8%  22.7    1s
H  579   311                     425.3662413  359.64884  15.4%  22.7    1s
*  664   289              14     416.7866861  360.57465  13.5%  22.8    2s
H  771   301                     413.5952392  361.83092  12.5%  22.3    2s
  1009   351  367.05086   22  109  413.59524  362.64054  12.3%  26.5    5s
* 2026   277              36     413.4133733  371.09649  10.2%  29.0    8s
  2417   308  378.07086   22   34  413.41337  372.64073  9.86%  29.2   10s
* 2637   298              36     413.3174205  373.82074  9.56%  29.8   10s
H 2781   291                     411.7982271  374.83692  8.98%  29.9   11s

Cutting planes:
  Learned: 33
  Gomory: 70
  Cover: 75
  Implied bound: 48
  Projected implied bound: 6
  Clique: 31
  MIR: 37
  Mixing: 7
  Flow cover: 139
  Inf proof: 7
  Zero half: 12
  RLT: 27
  Relax-and-lift: 13
  BQP: 8

Explored 4128 nodes (114352 simplex iterations) in 14.29 seconds (7.42 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 411.798 413.317 413.413 ... 441.812

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo Presolve = 0 I1!
Tiempo de ejecución: 14.29
Valor objetivo: 411.79822714269534
Gap final: 0.0

In [12]:
modelo_presolve_I2 = optimizar_modelo_presolve(datos_2)
reporte_modelo(modelo_presolve_I2, "modelo Presolve = 0", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Presolve to value 0
¡Optimizando modelo con presolve = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Presolve  0
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Variable types: 46 continuous, 1314 integer (1314 binary)

Root relaxation: objective 5.394012e+02, 455 iterations, 0.02 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  129          -  539.40121      -     -    0s
     0     0  561.50180    0  220          -  561.50180      -     -    0s
     0     0  590.87219    0  102          -  590.87219      -     -    0s
     0     0  590.87219    0  107          -  590.87219      -     -    0s
     0     0  590.87219    0  102          -  590.87219      -     -    0s
     0     0  590.87219    0  102          -  590.87219      -     -    0s
     0     0  592.31257    0  114          -  592.31257      -     -    0s
     0     0  593.54128    0  135          -  593.54128      -     -    0s
     0     0  593.72453    0  111          -  593.72453      -     -    0s
     0     0  593.75988    0  110          -  593.75988      -     -    0s
     0     0  600.87344    0  108          -  600.87344      -     -    0s
     0     0  602.32609    0  113          -  602.32609      -     -    0s
     0     0  602.32609    0  113          -  602.32609      -     -    0s
     0     0  602.47951    0  118          -  602.47951      -     -    0s
     0     0  602.82256    0  122          -  602.82256      -     -    0s
     0     0  602.82256    0  124          -  602.82256      -     -    0s
     0     0  603.34487    0  102          -  603.34487      -     -    0s
     0     0  603.34487    0  102          -  603.34487      -     -    0s
     0     0  603.34487    0  102          -  603.34487      -     -    0s
     0     0  603.34487    0  102          -  603.34487      -     -    0s
     0     0  603.34487    0  102          -  603.34487      -     -    0s
     0     2  603.36988    0  102          -  603.36988      -     -    0s
   655   467  657.21284   16  143          -  614.38838      -  19.2    5s
H  693   466                     899.5290313  618.47771  31.2%  26.7    8s
H  694   443                     896.5884494  618.47771  31.0%  26.7    9s
H  719   435                     856.5048612  618.47771  27.8%  28.9    9s
H  719   414                     835.8503948  618.47771  26.0%  28.9    9s
H  720   394                     815.1959284  618.47771  24.1%  28.8    9s
   722   397  666.92109   27   86  815.19593  618.47771  24.1%  28.9   10s
H  879   441                     804.3606471  619.23479  23.0%  34.4   13s
  1039   502 infeasible   43       804.36065  621.03496  22.8%  37.4   15s
  1748   767  705.82620   22  155  804.36065  624.60414  22.3%  42.2   20s
  2657  1315  683.35505   26  103  804.36065  628.61603  21.8%  41.5   25s
  3703  1936  665.93892   23   80  804.36065  637.24270  20.8%  40.9   30s
H 4029  2089                     797.5408693  638.44950  19.9%  40.7   31s
H 4358  2207                     788.1398625  639.88446  18.8%  40.7   33s
H 4358  2147                     782.3284742  639.88446  18.2%  40.7   33s
H 4358  2098                     778.4417976  639.88446  17.8%  40.7   33s
H 4358  2053                     775.3367876  639.88446  17.5%  40.7   33s
H 4358  2020                     772.2317776  639.88446  17.1%  40.7   33s
  4573  2102  663.37151   19   70  772.23178  640.72804  17.0%  41.0   35s
  5519  2601  756.36044   32   95  772.23178  644.49769  16.5%  40.6   40s
  6744  3209  686.74155   27  100  772.23178  647.47058  16.2%  39.2   45s
  7739  3735 infeasible   26       772.23178  649.67983  15.9%  39.1   50s
  8662  4211 infeasible   18       772.23178  651.05604  15.7%  38.8   55s
  9591  4671  665.55014   27  136  772.23178  653.08656  15.4%  38.7   60s
 10203  5003  687.13874   33  102  772.23178  653.83326  15.3%  38.7   70s
 10231  5022  697.26889   44  328  772.23178  653.83326  15.3%  38.6   75s
 10252  5036  694.60681   32  335  772.23178  653.83326  15.3%  38.5   80s
 10266  5045  743.13554   48  328  772.23178  653.83326  15.3%  38.4   85s
 10286  5058  729.26968   30  342  772.23178  653.83326  15.3%  38.4   90s
 10316  5078  692.54655   48  356  772.23178  653.83326  15.3%  38.3   95s
 10542  5150  739.55356   56   51  772.23178  653.83326  15.3%  40.3  100s
 10849  5186  653.85670   32  149  772.23178  653.83326  15.3%  41.3  105s
 11098  5219  728.41178   53   70  772.23178  654.94426  15.2%  42.0  110s
 11353  5257  683.33790   36  109  772.23178  657.80991  14.8%  42.5  115s
H11727  5068                     769.2419314  660.17985  14.2%  43.0  119s
 11734  5075  733.07637   48   75  769.24193  660.17985  14.2%  43.0  120s
 12026  5120  666.33022   32  126  769.24193  663.43412  13.8%  43.5  125s
 12728  5238  759.80002   47   44  769.24193  667.04639  13.3%  43.8  130s
 13250  5298  703.99677   40   83  769.24193  669.48991  13.0%  44.1  135s
 13945  5371 infeasible   43       769.24193  673.27680  12.5%  44.3  140s
 14767  5409  763.34425   49   41  769.24193  676.47213  12.1%  44.7  145s
 15689  5510  755.81312   43  112  769.24193  679.22771  11.7%  44.6  150s
 16726  5664  719.18181   38   90  769.24193  682.22837  11.3%  44.6  155s
 17636  5755  736.21290   50  127  769.24193  684.41430  11.0%  44.2  160s
 18690  5856  723.94091   41   87  769.24193  686.03263  10.8%  43.8  165s
 19856  5999  732.66314   41  151  769.24193  688.46751  10.5%  43.4  170s
 20953  6088     cutoff   40       769.24193  690.00338  10.3%  43.1  175s
 22436  6171  706.78101   39   70  769.24193  691.60218  10.1%  42.5  180s
 23807  6303  736.37289   52   58  769.24193  693.65006  9.83%  42.0  185s
 25038  6443  697.61231   41  118  769.24193  695.48142  9.59%  41.6  190s
 26450  6997  757.47117   55   70  769.24193  697.15650  9.37%  41.1  195s
 27884  7474  769.09208   45   47  769.24193  698.77440  9.16%  40.8  200s
 29469  8045     cutoff   53       769.24193  700.19841  8.98%  40.3  205s
 31090  8698  757.13207   43   52  769.24193  701.62897  8.79%  39.8  210s
 32793  9318  707.80947   44  140  769.24193  702.74193  8.64%  39.2  215s
 34421  9943  757.68342   45   43  769.24193  703.91948  8.49%  38.9  220s
 36383 10591  753.77394   36  138  769.24193  705.08814  8.34%  38.4  225s
 38067 11165  762.08190   45   55  769.24193  706.11894  8.21%  38.1  230s
 39429 11661  724.42589   40  157  769.24193  706.88151  8.11%  37.8  235s
 40971 12298  766.33439   50   37  769.24193  707.85483  7.98%  37.4  240s
 42651 12890  765.64709   40   92  769.24193  708.61299  7.88%  37.0  245s
 44258 13477  728.06412   37  128  769.24193  709.35192  7.79%  36.8  250s
 45862 14033  735.41584   50  108  769.24193  710.11496  7.69%  36.5  255s
 47465 14607  716.52209   41   65  769.24193  710.96711  7.58%  36.2  260s
 49082 15143  745.02734   43   54  769.24193  711.76367  7.47%  36.0  265s
 50623 15671  733.95096   50  136  769.24193  712.41747  7.39%  35.7  270s
 52245 16214  734.72256   39   79  769.24193  712.97722  7.31%  35.5  275s
 53800 16714  739.38195   41  111  769.24193  713.66441  7.22%  35.3  280s
 55290 17134  757.48156   49   56  769.24193  714.36448  7.13%  35.2  285s
 56931 17539  741.90670   40   97  769.24193  714.85831  7.07%  35.0  290s
 58497 17952  768.68542   50   45  769.24193  715.39942  7.00%  34.8  295s
 60226 18423  753.52512   36   64  769.24193  715.92154  6.93%  34.6  300s
 61984 18878  751.64068   46   80  769.24193  716.47240  6.86%  34.4  305s
 63623 19300  722.11727   50  117  769.24193  716.99660  6.79%  34.3  310s
 65129 19696  737.85700   43  109  769.24193  717.54197  6.72%  34.2  315s
 66620 20087  742.68650   39   94  769.24193  718.02172  6.66%  34.0  321s
 67959 20443  749.57621   46   35  769.24193  718.38626  6.61%  33.9  325s
 69742 20906  726.69106   39   89  769.24193  718.89522  6.54%  33.8  330s
 71337 21279  727.47450   40  103  769.24193  719.39329  6.48%  33.6  335s
 73108 21745  754.60724   44   85  769.24193  719.80657  6.43%  33.5  340s
 74863 22202  764.82018   41   42  769.24193  720.23636  6.37%  33.3  345s
 76602 22673  749.19307   56   52  769.24193  720.82552  6.29%  33.2  350s
 78351 23091 infeasible   51       769.24193  721.25470  6.24%  33.1  355s
 79954 23465  742.19369   50   67  769.24193  721.61464  6.19%  32.9  360s
 81796 23865  745.44934   45   47  769.24193  722.00023  6.14%  32.8  365s
 83536 24245  739.57312   42   87  769.24193  722.38732  6.09%  32.7  370s
 85260 24634  742.11776   43   70  769.24193  722.76961  6.04%  32.6  375s
 86998 24995  740.05807   40  100  769.24193  723.08727  6.00%  32.5  380s
 88688 25340  730.78677   50   84  769.24193  723.45906  5.95%  32.4  385s
 90473 25700  738.45279   50  132  769.24193  723.77650  5.91%  32.2  390s
 92397 26112  762.65866   55   35  769.24193  724.17114  5.86%  32.1  395s
 94324 26450     cutoff   48       769.24193  724.62631  5.80%  31.9  400s
 96053 26800  744.55084   50  134  769.24193  724.95578  5.76%  31.8  405s
 97971 27225  735.32175   47   70  769.24193  725.33340  5.71%  31.7  410s
 99739 27486  743.55707   43   64  769.24193  725.73767  5.66%  31.5  415s
 101769 27869  765.32860   47   86  769.24193  726.15013  5.60%  31.4  420s
 103672 28211     cutoff   46       769.24193  726.52113  5.55%  31.3  425s
 105474 28526  764.39221   52   39  769.24193  726.83065  5.51%  31.2  430s
 107442 28901  752.00289   46  118  769.24193  727.16554  5.47%  31.0  435s
 109529 29313  761.22144   48   86  769.24193  727.51996  5.42%  30.9  440s
 111414 29657  759.59645   45  102  769.24193  727.86928  5.38%  30.8  445s
 113430 30004  747.26835   41   70  769.24193  728.23355  5.33%  30.6  450s
 115197 30352  753.42534   52  110  769.24193  728.52955  5.29%  30.5  455s
 117286 30667     cutoff   45       769.24193  728.89378  5.25%  30.4  460s
 119030 30940  741.04607   51   71  769.24193  729.23436  5.20%  30.3  465s
 120954 31224  747.05820   50   69  769.24193  729.54766  5.16%  30.3  470s
 122990 31495  743.55241   47   39  769.24193  729.87940  5.12%  30.2  475s
 125054 31865  759.27119   46  118  769.24193  730.18019  5.08%  30.1  480s
 126897 32094  763.13064   52   66  769.24193  730.45623  5.04%  30.0  485s
 128926 32435  743.87153   47  110  769.24193  730.74648  5.00%  29.9  490s
 130852 32729  747.43602   39   71  769.24193  731.02650  4.97%  29.8  495s
 132901 33092  763.67612   40  130  769.24193  731.29361  4.93%  29.7  500s
 134841 33402  764.26895   47   35  769.24193  731.57110  4.90%  29.6  505s
 136777 33735  756.75512   45   62  769.24193  731.81952  4.86%  29.6  510s
 138680 34043  756.26118   58   55  769.24193  732.03507  4.84%  29.5  515s
 140799 34375  741.85414   40  109  769.24193  732.27730  4.81%  29.4  520s
 142740 34619  762.97238   49   50  769.24193  732.57510  4.77%  29.3  525s
 144664 34829  744.40839   47   85  769.24193  732.87444  4.73%  29.2  530s
 146571 35053  744.27984   47   90  769.24193  733.16996  4.69%  29.2  535s
 148407 35328  759.94508   54   46  769.24193  733.40118  4.66%  29.1  540s
 150398 35605     cutoff   44       769.24193  733.65243  4.63%  29.0  545s
 152045 35818  761.01543   56  111  769.24193  733.86458  4.60%  29.0  550s
 153945 35998  768.58842   53   29  769.24193  734.10959  4.57%  28.9  555s
 155962 36226     cutoff   54       769.24193  734.36526  4.53%  28.8  560s
 157783 36392  758.33490   49   58  769.24193  734.58078  4.51%  28.8  565s
 159626 36561  752.10679   43  139  769.24193  734.81534  4.48%  28.7  570s
 161497 36829  746.42483   46   82  769.24193  735.02358  4.45%  28.6  575s
 163559 37002     cutoff   53       769.24193  735.24582  4.42%  28.6  580s
 165691 37244     cutoff   46       769.24193  735.49669  4.39%  28.5  585s
 167777 37436  745.84965   44   85  769.24193  735.73903  4.36%  28.4  590s
 169795 37696  743.06034   45   84  769.24193  735.96385  4.33%  28.3  595s

Cutting planes:
  Learned: 50
  Gomory: 1
  Lift-and-project: 1
  Cover: 523
  Implied bound: 204
  Projected implied bound: 69
  Clique: 64
  MIR: 51
  Mixing: 2
  StrongCG: 1
  Flow cover: 243
  GUB cover: 2
  Inf proof: 29
  Zero half: 170
  RLT: 32
  Relax-and-lift: 59
  BQP: 22

Explored 171838 nodes (4858263 simplex iterations) in 600.02 seconds (364.46 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 769.242 772.232 775.337 ... 835.85

Time limit reached
Best objective 7.692419314269e+02, best bound 7.362390271746e+02, gap 4.2903%

¡Reporte modelo Presolve = 0 I2!
Tiempo de ejecución: 600.02
Valor objetivo: 769.2419314269121
Gap final: 0.04290315296656379

### Modelo MIPFocus = 1

In [13]:
modelo_mipfocus1_I1 = optimizar_modelo_mipfocus_1(datos_1)
reporte_modelo(modelo_mipfocus1_I1, "modelo MIPFocus = 1", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter MIPFocus to value 1
¡Optimizando modelo con MIPFocus = 1!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
MIPFocus  1
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 783 rows and 397 columns
Presolve time: 0.03s
Presolved: 645 rows, 890 columns, 3102 nonzeros
Variable types: 32 continuous, 858 integer (858 binary)

Root relaxation: objective 2.239768e+02, 325 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0   98          -  223.97683      -     -    0s
H    0     0                     486.7936321  223.97683  54.0%     -    0s
     0     0  244.81360    0  140  486.79363  244.81360  49.7%     -    0s
H    0     0                     485.4651969  244.81360  49.6%     -    0s
     0     0  306.83096    0   62  485.46520  306.83096  36.8%     -    0s
     0     0  308.30499    0   53  485.46520  308.30499  36.5%     -    0s
     0     0  308.82915    0   39  485.46520  308.82915  36.4%     -    0s
     0     0  323.42376    0   62  485.46520  323.42376  33.4%     -    0s
     0     0  330.89081    0  166  485.46520  330.89081  31.8%     -    0s
     0     0  331.50378    0  165  485.46520  331.50378  31.7%     -    0s
     0     0  331.75595    0  164  485.46520  331.75595  31.7%     -    0s
     0     0  333.20689    0   49  485.46520  333.20689  31.4%     -    0s
     0     0  333.65713    0  158  485.46520  333.65713  31.3%     -    0s
     0     0  334.06149    0  155  485.46520  334.06149  31.2%     -    0s
     0     0  334.16520    0  150  485.46520  334.16520  31.2%     -    0s
     0     0  349.27698    0  137  485.46520  349.27698  28.1%     -    0s
H    0     0                     485.1070033  349.27698  28.0%     -    0s
     0     0  349.27698    0  137  485.10700  349.27698  28.0%     -    0s
     0     0  355.45531    0  146  485.10700  355.45531  26.7%     -    0s
     0     0  355.45883    0  146  485.10700  355.45883  26.7%     -    0s
     0     0  355.46161    0  145  485.10700  355.46161  26.7%     -    0s
H    0     0                     484.8727717  355.46161  26.7%     -    0s
     0     0  356.22627    0  148  484.87277  356.22627  26.5%     -    0s
     0     0  356.23493    0  144  484.87277  356.23493  26.5%     -    0s
     0     0  357.39837    0  156  484.87277  357.39837  26.3%     -    0s
     0     0  357.39837    0  156  484.87277  357.39837  26.3%     -    0s
H    0     0                     483.2711174  357.76207  26.0%     -    0s
H    0     0                     419.2177568  357.76207  14.7%     -    0s
     0     2  357.76207    0  156  419.21776  357.76207  14.7%     -    0s
H    1     1                     416.2533820  357.76207  14.1%   0.0    0s
H   46    32                     414.5346037  358.30248  13.6%  23.9    0s
  1737   255  382.08509   17   66  414.53460  372.51153  10.1%  19.6    5s
* 3644   160              13     413.5952392  383.09286  7.37%  19.6    9s
  3790   110  391.02975   19   24  413.59524  388.67985  6.02%  19.6   10s
* 3839    94              16     411.7982271  390.95136  5.06%  19.6   10s

Cutting planes:
  Learned: 62
  Gomory: 1
  Cover: 15
  Implied bound: 18
  Clique: 32
  MIR: 28
  Inf proof: 1
  Zero half: 3
  RLT: 14
  Relax-and-lift: 25
  BQP: 6

Explored 4216 nodes (80533 simplex iterations) in 10.52 seconds (4.90 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 411.798 413.595 414.535 ... 486.794

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo MIPFocus = 1 I1!
Tiempo de ejecución: 10.53
Valor objetivo: 411.79822714269534
Gap final: 0.0

In [27]:
modelo_mipfocus1_I2 = optimizar_modelo_mipfocus_1(datos_2)
reporte_modelo(modelo_mipfocus1_I2, "modelo MIPFocus = 1", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter MIPFocus to value 1
¡Optimizando modelo con MIPFocus = 1!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
MIPFocus  1
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.02s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)

Root relaxation: objective 5.394012e+02, 540 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  103          -  539.40121      -     -    0s
     0     0  547.20910    0  228          -  547.20910      -     -    0s
     0     0  590.32566    0  179          -  590.32566      -     -    0s
     0     0  591.24772    0   86          -  591.24772      -     -    0s
     0     0  598.71484    0  195          -  598.71484      -     -    0s
     0     0  601.88032    0  191          -  601.88032      -     -    0s
     0     0  601.94754    0  137          -  601.94754      -     -    0s
     0     0  601.94754    0  137          -  601.94754      -     -    0s
     0     0  608.23319    0  217          -  608.23319      -     -    0s
     0     0  608.91116    0  210          -  608.91116      -     -    0s
     0     0  608.97063    0  207          -  608.97063      -     -    0s
     0     0  608.97380    0  204          -  608.97380      -     -    0s
     0     0  611.44057    0  158          -  611.44057      -     -    0s
     0     0  611.62683    0  141          -  611.62683      -     -    0s
     0     0  611.62994    0  138          -  611.62994      -     -    0s
     0     0  612.53833    0  150          -  612.53833      -     -    0s
     0     0  612.53833    0  147          -  612.53833      -     -    0s
H    0     0                    1179.6018820  612.53833  48.1%     -    0s
     0     2  613.49321    0  147 1179.60188  613.49321  48.0%     -    0s
H   59    35                    1155.6802539  614.85521  46.8%  28.1    0s
H   59    35                    1149.1627583  614.85521  46.5%  28.1    0s
H   59    35                    1149.0789544  614.85521  46.5%  28.1    0s
H   59    35                    1145.8200828  614.85521  46.3%  28.1    0s
H   59    35                    1145.6474797  614.85521  46.3%  28.1    0s
H   59    35                    1142.1375647  614.85521  46.2%  28.1    0s
H   59    35                    1132.0194425  614.85521  45.7%  28.1    0s
H   59    35                    1131.9356387  614.85521  45.7%  28.1    0s
H   62    34                    1125.8365837  614.85521  45.4%  27.0    0s
H   87    41                    1116.4013954  616.24160  44.8%  25.6    0s
H   87    41                    1110.0614133  616.24160  44.5%  25.6    0s
H   87    41                    1046.1680468  616.24160  41.1%  25.6    0s
H  177    95                    1012.6551114  620.61255  38.7%  26.2    0s
H  177    95                    1004.9172465  620.61255  38.2%  26.2    0s
H  177    95                     991.9060303  620.61255  37.4%  26.2    0s
H  177    95                     985.6744276  620.61255  37.0%  26.2    0s
H  203   119                     983.6039862  620.61255  36.9%  24.5    1s
H  412   207                     977.8225621  622.08972  36.4%  19.0    1s
H  719   389                     967.3480739  625.49101  35.3%  17.6    1s
H  725   373                     959.8493932  625.49101  34.8%  17.5    1s
H  728   356                     956.8620800  625.49666  34.6%  17.4    2s
H  728   338                     955.3439694  625.49666  34.5%  17.4    2s
H  730   321                     952.7044596  625.49666  34.3%  19.8    2s
H  730   305                     946.7530809  625.49666  33.9%  19.8    2s
H  730   290                     946.3848010  625.49666  33.9%  19.8    2s
H  730   275                     914.7845111  625.49666  31.6%  19.8    2s
H  730   261                     904.6558714  625.49666  30.9%  19.8    2s
H  748   247                     893.2142983  625.49666  30.0%  21.4    2s
H  756   241                     883.6142459  625.49666  29.2%  22.3    2s
H  766   235                     871.8178387  625.49666  28.3%  22.6    2s
H  768   225                     868.3122296  625.49666  28.0%  22.6    2s
H  768   214                     857.5477904  625.49666  27.1%  22.6    2s
H  771   202                     851.8122906  625.49666  26.6%  22.6    2s
H  777   188                     837.2926861  625.49666  25.3%  22.8    2s
H 1265   238                     806.1916288  639.79796  20.6%  29.5    4s
* 1272   242              38     804.1106522  639.79796  20.4%  29.4    4s
  1680   439  713.59407   37   53  804.11065  654.97764  18.5%  29.8    5s
H 1963   546                     799.6057498  658.35202  17.7%  29.5    5s
H 1963   524                     788.5352661  658.35202  16.5%  29.5    5s
H 1975   505                     780.4791053  658.50704  15.6%  29.5    5s
H 2975   878                     775.2900138  664.51289  14.3%  28.2    7s
  5218  1712  713.16475   29   52  775.29001  674.47473  13.0%  23.8   10s
 10856  3752  749.68405   34   44  775.29001  685.04026  11.6%  19.6   15s
 17909  5927  723.42041   35   37  775.29001  691.68371  10.8%  17.8   20s
 24809  7989  757.85671   30   36  775.29001  695.73559  10.3%  16.8   25s
 31637  9781  718.32296   34   50  775.29001  698.76779  9.87%  16.1   30s
 37565 11300  707.76158   27   45  775.29001  700.76803  9.61%  15.7   35s
 43520 12760  733.30668   36   72  775.29001  702.52314  9.39%  15.4   40s
 49253 14159  759.43053   44   51  775.29001  704.07280  9.19%  15.3   45s
 55887 15648  724.27957   37   37  775.29001  705.76083  8.97%  15.1   50s
 61984 16948  714.65614   34   63  775.29001  707.06125  8.80%  14.9   55s
 68766 18356  748.31555   34   78  775.29001  708.34279  8.64%  14.7   60s
 75304 19627     cutoff   36       775.29001  709.54169  8.48%  14.5   65s
 81765 20800  731.82254   31   28  775.29001  710.60952  8.34%  14.4   70s
 88991 22125  737.26910   36   56  775.29001  711.76120  8.19%  14.2   75s
 96176 23451  724.79235   32   83  775.29001  712.83966  8.06%  14.1   80s
 103193 24713  731.68226   29   76  775.29001  713.63801  7.95%  13.9   85s
 111415 26062  745.13448   33   31  775.29001  714.77036  7.81%  13.8   90s
 117512 27086  747.07021   36   56  775.29001  715.49300  7.71%  13.7   95s
 123953 28239  716.31504   36   34  775.29001  716.26040  7.61%  13.6  100s
 129843 29087  766.70928   34   81  775.29001  716.90493  7.53%  13.6  105s
*134486 29879              44     775.2003492  717.48575  7.45%  13.5  108s
H134488 29776                     773.3724173  717.48575  7.23%  13.5  108s
H134488 29362                     769.2419314  717.48575  6.73%  13.5  108s
 135773 29478  736.07355   42   40  769.24193  717.64020  6.71%  13.5  110s
 143000 30367  744.51476   47   47  769.24193  718.52012  6.59%  13.5  115s
 150649 31340  728.70551   34   42  769.24193  719.41044  6.48%  13.4  120s
 157057 32096     cutoff   36       769.24193  720.14584  6.38%  13.3  125s
 165151 32996  758.14176   37   35  769.24193  720.95561  6.28%  13.3  130s
 171982 33663  758.10030   38   43  769.24193  721.61558  6.19%  13.2  135s
 178733 34386  755.98450   36   52  769.24193  722.30903  6.10%  13.2  140s
 185697 35106  763.72325   35   46  769.24193  722.91360  6.02%  13.2  145s
 193395 35787  734.46738   36   55  769.24193  723.67529  5.92%  13.1  150s
 200023 36374  758.59781   47   32  769.24193  724.24130  5.85%  13.1  155s
 208073 37004 infeasible   35       769.24193  724.89648  5.76%  13.0  160s
 214859 37634  751.14995   36   64  769.24193  725.42573  5.70%  13.0  165s
 223309 38307     cutoff   39       769.24193  726.15681  5.60%  12.9  170s
 231628 39002  759.99764   44   38  769.24193  726.83805  5.51%  12.8  175s
 239435 39556  765.80707   29  116  769.24193  727.45379  5.43%  12.7  180s
 248300 40189  752.97746   41   33  769.24193  728.08328  5.35%  12.7  185s
 254473 40711  741.27367   32   69  769.24193  728.56984  5.29%  12.6  190s
 262497 41311  729.82152   32   46  769.24193  729.13591  5.21%  12.6  195s
 270919 41842  754.37500   43   81  769.24193  729.70258  5.14%  12.5  200s
 279946 42410  759.54558   34   60  769.24193  730.29922  5.06%  12.4  205s
 288697 42958  735.50401   37   44  769.24193  730.88130  4.99%  12.4  210s
 297300 43512  760.17587   43   55  769.24193  731.41670  4.92%  12.3  215s
 306060 43999     cutoff   50       769.24193  731.97561  4.84%  12.3  220s
 314692 44466 infeasible   41       769.24193  732.54082  4.77%  12.2  225s
 323892 44827  748.74832   37   50  769.24193  733.05475  4.70%  12.1  230s
 331892 45179  753.14022   42   40  769.24193  733.49627  4.65%  12.1  235s
 341332 45506     cutoff   41       769.24193  734.00327  4.58%  12.0  240s
 348482 45778  754.95785   40   66  769.24193  734.41091  4.53%  12.0  245s
 358148 46013  738.68549   37   54  769.24193  734.90383  4.46%  11.9  250s
 367418 46275  736.32797   43   70  769.24193  735.37864  4.40%  11.9  255s
 375587 46444  737.13611   43   40  769.24193  735.81440  4.35%  11.8  260s
 384679 46636  760.09040   52   22  769.24193  736.28567  4.28%  11.8  265s
 393536 46855  760.00133   37   74  769.24193  736.72550  4.23%  11.7  270s
 402026 47018  751.93524   46   40  769.24193  737.19131  4.17%  11.7  275s
 410488 46993  749.35719   50   21  769.24193  737.64402  4.11%  11.6  280s
 419759 47041  748.09225   40   69  769.24193  738.10008  4.05%  11.6  286s
 426595 47010  753.13421   42   43  769.24193  738.43413  4.00%  11.5  290s
 435422 47028  755.67418   48   20  769.24193  738.84492  3.95%  11.5  295s
 444622 46890  756.77183   39   16  769.24193  739.28395  3.89%  11.5  300s
 452873 46779  744.41968   46   25  769.24193  739.68776  3.84%  11.4  305s
 460537 46587 infeasible   47       769.24193  740.09294  3.79%  11.4  310s
 468727 46409     cutoff   41       769.24193  740.47851  3.74%  11.4  315s
 476468 46165  760.57439   36   62  769.24193  740.85578  3.69%  11.4  320s
 484235 45849 infeasible   40       769.24193  741.25337  3.64%  11.4  325s
 492512 45377 infeasible   45       769.24193  741.70276  3.58%  11.3  330s
 501281 44906  749.60084   37   47  769.24193  742.16336  3.52%  11.3  335s
 509701 44489  743.04149   31   60  769.24193  742.60302  3.46%  11.3  340s
 515975 44096  749.15208   38   63  769.24193  742.91786  3.42%  11.3  345s
 524718 43517  765.85972   39   61  769.24193  743.34485  3.37%  11.3  350s
 532856 42776 infeasible   35       769.24193  743.78075  3.31%  11.3  355s
 541843 41983  763.46573   49   29  769.24193  744.24727  3.25%  11.2  360s
 550171 41246  748.56512   37   60  769.24193  744.69485  3.19%  11.2  365s
 558385 40481  751.52674   37   60  769.24193  745.15263  3.13%  11.2  370s
 566884 39447  766.05860   41   59  769.24193  745.66908  3.06%  11.2  375s
 575439 38525  760.08510   37   64  769.24193  746.14498  3.00%  11.2  380s
 583402 37582  753.16005   46   34  769.24193  746.57724  2.95%  11.2  385s
 592297 36443  758.95016   35   36  769.24193  747.13336  2.87%  11.1  390s
 599875 35216  748.95024   35   60  769.24193  747.64793  2.81%  11.1  395s
 608798 33863  755.59959   50   26  769.24193  748.24456  2.73%  11.1  400s
 616962 32451     cutoff   33       769.24193  748.81881  2.65%  11.1  405s
 624885 31012     cutoff   30       769.24193  749.38421  2.58%  11.1  410s
 632749 29394  761.29466   46   52  769.24193  750.01707  2.50%  11.1  415s
 641304 27493  767.06806   36   41  769.24193  750.76341  2.40%  11.1  420s
 648835 25707  760.86616   38   54  769.24193  751.48118  2.31%  11.1  425s
 657413 23590  758.41216   39   69  769.24193  752.30221  2.20%  11.0  430s
 665796 21240 infeasible   34       769.24193  753.21129  2.08%  11.0  435s
 674266 18458 infeasible   39       769.24193  754.32751  1.94%  11.0  440s
 682272 15625     cutoff   43       769.24193  755.54338  1.78%  11.0  445s
 691020 11880  759.38819   50   12  769.24193  757.22022  1.56%  11.0  450s
 699065  7813  767.07206   27  126  769.24193  759.47588  1.27%  11.0  455s
 703967  4819  766.93252   40   20  769.24193  761.73946  0.98%  10.9  460s

Cutting planes:
  Learned: 165
  Gomory: 1
  Lift-and-project: 4
  Cover: 27
  Implied bound: 32
  Clique: 40
  MIR: 21
  StrongCG: 2
  Flow cover: 28
  GUB cover: 6
  Inf proof: 43
  Zero half: 4
  Mod-K: 1
  RLT: 9
  Relax-and-lift: 21
  BQP: 15

Explored 709834 nodes (7741893 simplex iterations) in 462.65 seconds (483.35 work units)
Thread count was 1 (of 16 available processors)

Solution count 10: 769.242 769.242 773.372 ... 806.192

Optimal solution found (tolerance 1.00e-04)
Best objective 7.692419314269e+02, best bound 7.691752620097e+02, gap 0.0087%

¡Reporte modelo MIPFocus = 1 I2!
Tiempo de ejecución: 462.66
Valor objetivo: 769.2419314269123
Gap final: 8.666898470036933e-05

### Modelo MIPFocus = 3

In [15]:
modelo_mipfocus3_I1 = optimizar_modelo_mipfocus_3(datos_1)
reporte_modelo(modelo_mipfocus3_I1, "modelo MIPFocus = 3", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter MIPFocus to value 3
¡Optimizando modelo con MIPFocus = 3!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
MIPFocus  3
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 783 rows and 397 columns
Presolve time: 0.03s
Presolved: 645 rows, 890 columns, 3102 nonzeros
Variable types: 32 continuous, 858 integer (858 binary)
Root relaxation presolved: 645 rows, 890 columns, 3102 nonzeros


Use crossover to convert LP symmetric solution to basic solution...
Crossover time: 0.00 seconds (0.00 work units)

Root relaxation: objective 2.239768e+02, 196 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0   98          -  223.97683      -     -    0s
H    0     0                     486.7936321  223.97683  54.0%     -    0s
     0     0  251.36476    0  184  486.79363  251.36476  48.4%     -    0s
     0     0  251.36476    0  184  486.79363  251.36476  48.4%     -    0s
H    0     0                     485.4651969  251.86373  48.1%     -    0s
H    0     0                     421.0536427  251.86373  40.2%     -    0s
     0     0  320.53690    0   66  421.05364  320.53690  23.9%     -    0s
     0     0  322.15028    0   61  421.05364  322.15028  23.5%     -    0s
     0     0  323.01968    0   77  421.05364  323.01968  23.3%     -    0s
     0     0  323.55710    0   53  421.05364  323.55710  23.2%     -    0s
     0     0  323.65142    0   53  421.05364  323.65142  23.1%     -    0s
     0     0  334.29084    0  175  421.05364  334.29084  20.6%     -    0s
     0     0  334.29084    0  175  421.05364  334.29084  20.6%     -    0s
     0     0  335.79717    0  205  421.05364  335.79717  20.2%     -    0s
     0     0  335.98280    0  205  421.05364  335.98280  20.2%     -    0s
     0     0  335.99102    0  207  421.05364  335.99102  20.2%     -    0s
     0     0  353.05708    0  204  421.05364  353.05708  16.1%     -    0s
     0     0  353.05708    0  204  421.05364  353.05708  16.1%     -    1s
     0     0  353.78739    0  184  421.05364  353.78739  16.0%     -    1s
     0     0  354.15805    0  182  421.05364  354.15805  15.9%     -    1s
     0     0  354.16924    0  180  421.05364  354.16924  15.9%     -    1s
     0     0  356.34165    0   24  421.05364  356.34165  15.4%     -    1s
     0     0  356.97137    0   24  421.05364  356.97137  15.2%     -    1s
     0     0  360.15689    0  147  421.05364  360.15689  14.5%     -    1s
     0     0  360.15689    0  147  421.05364  360.15689  14.5%     -    1s
     0     0  361.10974    0   52  421.05364  361.10974  14.2%     -    1s
H    0     0                     420.8194111  361.11773  14.2%     -    1s
     0     0  361.11773    0   52  420.81941  361.11773  14.2%     -    1s
     0     0  363.32737    0  215  420.81941  363.32737  13.7%     -    2s
     0     0  363.35038    0  226  420.81941  363.35038  13.7%     -    2s
     0     0  364.29627    0  253  420.81941  364.29627  13.4%     -    2s
     0     0  364.35490    0  253  420.81941  364.35490  13.4%     -    2s
     0     0  364.35490    0  253  420.81941  364.35490  13.4%     -    2s
     0     0  364.35490    0  253  420.81941  364.35490  13.4%     -    2s
H    0     0                     416.1362581  364.44231  12.4%     -    2s
     0     0  364.44231    0  111  416.13626  364.44231  12.4%     -    2s
     0     0  364.44231    0  133  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  136  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  127  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  228  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  237  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  244  416.13626  364.44231  12.4%     -    3s
     0     0  364.44231    0  211  416.13626  364.44231  12.4%     -    3s
     0     0  365.16960    0  254  416.13626  365.16960  12.2%     -    3s
     0     0  365.19718    0  249  416.13626  365.19718  12.2%     -    3s
     0     0  365.85048    0  234  416.13626  365.85048  12.1%     -    4s
     0     0  365.88346    0  234  416.13626  365.88346  12.1%     -    4s
     0     2  365.92413    0  234  416.13626  365.92413  12.1%     -    4s
H    2     2                     414.5346037  365.96412  11.7%  27.5    4s
     7     9  369.25158    3   47  414.53460  368.25602  11.2%   178    5s
*  311    47               8     413.5952392  410.34720  0.79%  49.9    8s
*  348     0              10     411.7982271  411.79823  0.00%  45.6    8s

Cutting planes:
  Learned: 36
  Gomory: 17
  Lift-and-project: 7
  Cover: 38
  Implied bound: 219
  Projected implied bound: 2
  Clique: 65
  MIR: 140
  Mixing: 17
  StrongCG: 10
  Flow cover: 277
  GUB cover: 4
  Zero half: 157
  RLT: 10
  Relax-and-lift: 154
  BQP: 23
  PSD: 2

Explored 349 nodes (20664 simplex iterations) in 8.89 seconds (4.96 work units)
Thread count was 1 (of 16 available processors)

Solution count 8: 411.798 413.595 414.535 ... 486.794

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo MIPFocus = 3 I1!
Tiempo de ejecución: 8.90
Valor objetivo: 411.79822714269534
Gap final: 0.0

In [16]:
modelo_mipfocus3_I2 = optimizar_modelo_mipfocus_3(datos_2)
reporte_modelo(modelo_mipfocus3_I2, "modelo MIPFocus = 3", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter MIPFocus to value 3
¡Optimizando modelo con MIPFocus = 3!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
MIPFocus  3
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.09s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)
Root relaxation presolved: 1194 rows, 1213 columns, 5331 nonzeros


Use crossover to convert LP symmetric solution to basic solution...
Crossover time: 0.00 seconds (0.00 work units)

Root relaxation: objective 5.394012e+02, 199 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0   99          -  539.40121      -     -    0s
     0     0  549.98728    0  162          -  549.98728      -     -    0s
     0     0  549.98728    0  161          -  549.98728      -     -    0s
     0     0  590.23049    0  128          -  590.23049      -     -    0s
     0     0  590.98294    0  115          -  590.98294      -     -    0s
     0     0  591.17336    0   95          -  591.17336      -     -    0s
     0     0  591.17336    0   95          -  591.17336      -     -    0s
     0     0  602.38690    0  199          -  602.38690      -     -    0s
     0     0  602.38690    0  157          -  602.38690      -     -    1s
     0     0  603.25892    0  120          -  603.25892      -     -    1s
     0     0  603.87908    0  152          -  603.87908      -     -    1s
     0     0  603.89537    0  114          -  603.89537      -     -    1s
     0     0  608.51739    0  186          -  608.51739      -     -    1s
     0     0  608.51739    0  186          -  608.51739      -     -    2s
     0     0  609.90671    0  192          -  609.90671      -     -    2s
     0     0  610.06860    0  188          -  610.06860      -     -    2s
     0     0  610.41323    0  219          -  610.41323      -     -    2s
     0     0  610.42260    0  157          -  610.42260      -     -    2s
     0     0  616.68290    0  109          -  616.68290      -     -    2s
     0     0  616.68290    0  109          -  616.68290      -     -    2s
     0     0  616.74854    0  135          -  616.74854      -     -    2s
     0     0  616.76137    0  106          -  616.76137      -     -    2s
     0     0  619.82205    0  200          -  619.82205      -     -    2s
     0     0  619.82205    0  199          -  619.82205      -     -    3s
     0     0  620.62732    0  231          -  620.62732      -     -    3s
     0     0  620.76201    0  219          -  620.76201      -     -    3s
     0     0  620.77572    0  223          -  620.77572      -     -    3s
     0     0  623.43257    0  193          -  623.43257      -     -    3s
     0     0  623.43257    0  193          -  623.43257      -     -    4s
     0     0  623.54781    0  146          -  623.54781      -     -    4s
     0     0  623.54781    0  147          -  623.54781      -     -    4s
     0     0  626.10766    0  248          -  626.10766      -     -    4s
     0     0  626.10766    0  239          -  626.10766      -     -    4s
     0     0  627.44809    0  219          -  627.44809      -     -    4s
     0     0  627.55893    0  207          -  627.55893      -     -    4s
     0     0  627.57445    0  194          -  627.57445      -     -    4s
     0     0  628.30906    0  244          -  628.30906      -     -    5s
     0     0  628.30906    0  244          -  628.30906      -     -    5s
     0     0  628.56588    0  242          -  628.56588      -     -    5s
     0     0  628.71690    0  189          -  628.71690      -     -    5s
     0     0  628.73362    0  225          -  628.73362      -     -    5s
     0     0  631.50742    0  164          -  631.50742      -     -    6s
     0     0  631.50742    0  162          -  631.50742      -     -    6s
     0     0  631.68691    0  246          -  631.68691      -     -    6s
     0     0  631.71448    0  255          -  631.71448      -     -    6s
     0     0  632.27714    0  242          -  632.27714      -     -    6s
     0     0  632.27714    0  238          -  632.27714      -     -    7s
     0     0  632.37174    0  253          -  632.37174      -     -    7s
     0     0  632.37196    0  254          -  632.37196      -     -    7s
     0     0  632.78458    0  225          -  632.78458      -     -    7s
     0     0  632.78458    0  214          -  632.78458      -     -    7s
     0     0  632.79081    0  222          -  632.79081      -     -    7s
     0     0  633.13534    0  228          -  633.13534      -     -    7s
     0     0  633.13534    0  222          -  633.13534      -     -    8s
     0     0  633.14557    0  222          -  633.14557      -     -    8s
     0     0  633.14557    0  222          -  633.14557      -     -    8s
     0     0  633.15034    0  105          -  633.15034      -     -    8s
     0     0  633.15034    0  211          -  633.15034      -     -    8s
     0     0  633.15034    0  211          -  633.15034      -     -    8s
     0     0  633.15034    0  156          -  633.15034      -     -    8s
     0     0  633.15034    0  218          -  633.15034      -     -    8s
     0     0  633.30448    0  236          -  633.30448      -     -    8s
     0     0  633.34882    0  234          -  633.34882      -     -    8s
     0     0  633.35139    0  236          -  633.35139      -     -    9s
     0     0  634.25808    0  241          -  634.25808      -     -    9s
     0     0  634.25808    0  241          -  634.25808      -     -    9s
     0     0  634.35376    0  235          -  634.35376      -     -    9s
     0     0  634.51539    0  236          -  634.51539      -     -    9s
     0     0  634.51539    0  237          -  634.51539      -     -    9s
     0     0  635.10828    0  244          -  635.10828      -     -   10s
     0     0  635.10828    0  244          -  635.10828      -     -   10s
     0     0  635.34738    0  239          -  635.34738      -     -   10s
     0     0  635.35656    0  202          -  635.35656      -     -   10s
     0     0  635.55414    0  255          -  635.55414      -     -   11s
     0     0  635.55414    0  255          -  635.55414      -     -   11s
     0     0  635.63780    0  248          -  635.63780      -     -   11s
     0     0  635.65987    0  247          -  635.65987      -     -   11s
     0     0  636.54275    0  268          -  636.54275      -     -   12s
     0     0  636.54275    0  264          -  636.54275      -     -   12s
     0     0  636.74539    0  271          -  636.74539      -     -   12s
     0     0  636.79558    0  265          -  636.79558      -     -   12s
     0     0  636.83219    0  265          -  636.83219      -     -   12s
     0     0  638.02866    0  272          -  638.02866      -     -   12s
     0     0  638.02866    0  272          -  638.02866      -     -   13s
     0     0  638.31378    0  275          -  638.31378      -     -   13s
     0     0  638.45121    0  281          -  638.45121      -     -   13s
     0     0  638.45882    0  278          -  638.45882      -     -   13s
     0     0  638.82852    0  285          -  638.82852      -     -   13s
     0     0  638.82852    0  279          -  638.82852      -     -   13s
     0     0  639.04493    0  276          -  639.04493      -     -   13s
     0     0  639.08355    0  274          -  639.08355      -     -   13s
     0     0  639.55263    0  277          -  639.55263      -     -   13s
     0     0  639.55263    0  276          -  639.55263      -     -   13s
     0     0  639.60646    0  276          -  639.60646      -     -   13s
     0     0  639.71336    0  306          -  639.71336      -     -   13s
     0     0  639.71336    0  306          -  639.71336      -     -   13s
     0     0  639.71814    0  306          -  639.71814      -     -   13s
     0     0  639.71814    0  305          -  639.71814      -     -   13s
     0     2  639.72991    0  303          -  639.72991      -     -   14s
     8    10  650.38450    3  133          -  642.58323      -   175   15s
H  359   355                     806.8717067  671.38444  16.8%  81.2   19s
   384   382  679.74676    8  105  806.87171  672.21720  16.7%  86.3   20s
H  528   477                     804.8799785  678.12934  15.7%   125   23s
H  529   453                     803.0520466  678.12934  15.6%   125   24s
   536   458  694.33713    8  272  803.05205  678.12934  15.6%   123   25s
H  536   435                     798.9215607  678.12934  15.1%   123   25s
H  536   413                     787.1658347  678.12934  13.9%   123   25s
H  555   405                     779.1096739  678.12934  13.0%   119   29s
   563   410  686.55813   10  288  779.10967  678.12934  13.0%   117   30s
H  571   393                     775.2900138  678.12934  12.5%   116   31s
   593   410  678.72933   16  167  775.29001  678.12934  12.5%   127   35s
   634   437  682.52378   16  183  775.29001  678.12934  12.5%   137   40s
   689   470  694.15549   19  189  775.29001  683.17017  11.9%   149   45s
   749   508  693.79862   28  147  775.29001  689.96697  11.0%   160   50s
   806   543  700.18296   26  178  775.29001  695.76804  10.3%   168   55s
   881   584  703.59668   22  135  775.29001  701.07466  9.57%   177   60s
   947   623  736.36934   21  146  775.29001  704.11264  9.18%   185   65s
  1047   686  712.89993   29  145  775.29001  710.02777  8.42%   192   70s
  1157   742  714.31917   28   93  775.29001  713.82798  7.93%   196   75s
  1283   814  722.96177   31  154  775.29001  717.76613  7.42%   198   80s
  1405   859  725.42878   21   72  775.29001  721.24748  6.97%   199   85s
  1540   918  728.26555   22   59  775.29001  724.34683  6.57%   199   90s
  1676   973  730.28056   26  179  775.29001  727.07032  6.22%   198   95s
  1820  1017  732.96982   23   64  775.29001  729.75520  5.87%   197  100s
  1974  1100  750.72658   21  125  775.29001  732.42641  5.53%   194  105s
  2099  1177  748.92548   21  158  775.29001  734.16218  5.30%   192  110s
  2279  1271  737.26012   39  158  775.29001  736.75270  4.97%   190  115s
  2489  1380  750.44694   23  156  775.29001  739.06496  4.67%   187  120s
  2720  1520  761.43015   33  120  775.29001  741.16432  4.40%   182  125s
  2947  1652  743.49031   29  145  775.29001  742.74329  4.20%   179  130s
  3173  1786  746.18574   25  143  775.29001  744.47195  3.98%   175  135s
H 3304  1769                     769.2419314  745.40223  3.10%   174  139s
  3333  1780  747.37974   25  141  769.24193  745.56346  3.08%   173  140s
  3627  1910  761.65828   25  121  769.24193  747.48499  2.83%   167  145s
  3926  2001     cutoff   22       769.24193  749.11765  2.62%   162  150s
  4231  2089  750.49144   39   77  769.24193  750.49144  2.44%   157  155s
  4571  2171  752.16643   27  106  769.24193  752.00178  2.24%   151  160s
  4904  2224  753.50376   28  209  769.24193  753.27631  2.08%   146  165s
  5240  2287  756.45139   22  125  769.24193  754.42087  1.93%   141  170s
  5546  2299  756.36525   33   60  769.24193  755.46289  1.79%   137  175s
  5878  2291     cutoff   22       769.24193  756.41803  1.67%   133  180s
  6234  2211     cutoff   36       769.24193  757.46725  1.53%   129  185s
  6587  2133  761.00287   32   70  769.24193  758.52580  1.39%   125  190s
  6978  2067  760.05568   24  133  769.24193  759.55272  1.26%   121  195s
  7364  1989  762.67676   34  155  769.24193  760.60935  1.12%   117  201s
  7694  1901  762.35765   31  177  769.24193  761.51411  1.00%   114  205s
  8249  1710     cutoff   31       769.24193  762.80921  0.84%   109  210s
  8856  1434  764.98636   36  105  769.24193  764.26578  0.65%   103  215s
  9664   961 infeasible   28       769.24193  766.16415  0.40%  96.6  220s

Cutting planes:
  Learned: 34
  Gomory: 1
  Lift-and-project: 14
  Cover: 361
  Implied bound: 729
  Projected implied bound: 4
  Clique: 180
  MIR: 108
  Mixing: 3
  StrongCG: 9
  Flow cover: 332
  GUB cover: 21
  Inf proof: 6
  Zero half: 910
  RLT: 69
  Relax-and-lift: 793
  BQP: 80

Explored 10782 nodes (953994 simplex iterations) in 223.76 seconds (169.79 work units)
Thread count was 1 (of 16 available processors)

Solution count 8: 769.242 775.29 779.11 ... 806.872

Optimal solution found (tolerance 1.00e-04)
Best objective 7.692419314269e+02, best bound 7.691731301449e+02, gap 0.0089%

¡Reporte modelo MIPFocus = 3 I2!
Tiempo de ejecución: 223.77
Valor objetivo: 769.2419314269123
Gap final: 8.944036870030442e-05

### Modelo Heuristics = 0

In [17]:
modelo_heuristics_I1 = optimizar_modelo_heuristics(datos_1)
reporte_modelo(modelo_heuristics_I1, "modelo Heuristics = 0", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Heuristics to value 0
¡Optimizando modelo con heuristics = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Heuristics  0
Threads  1

Optimize a model with 1428 rows, 1287 columns and 6300 nonzeros (Min)
Model fingerprint: 0xcbc56733
Model has 1188 linear objective coefficients
Variable types: 45 continuous, 1242 integer (1242 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+01]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 783 rows and 397 columns
Presolve time: 0.02s
Presolved: 645 rows, 890 columns, 3102 nonzeros
Variable types: 32 continuous, 858 integer (858 binary)

Root relaxation: objective 2.239768e+02, 325 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  223.97683    0   98          -  223.97683      -     -    0s
     0     0  242.72491    0  189          -  242.72491      -     -    0s
     0     0  306.83096    0   62          -  306.83096      -     -    0s
     0     0  308.30499    0   53          -  308.30499      -     -    0s
     0     0  308.82601    0   51          -  308.82601      -     -    0s
     0     0  308.82915    0   40          -  308.82915      -     -    0s
     0     0  332.29823    0   50          -  332.29823      -     -    0s
     0     0  333.20689    0   49          -  333.20689      -     -    0s
     0     0  333.64746    0  147          -  333.64746      -     -    0s
     0     0  333.77203    0  155          -  333.77203      -     -    0s
     0     0  333.86079    0  151          -  333.86079      -     -    0s
     0     0  333.99136    0  149          -  333.99136      -     -    0s
     0     0  333.99767    0  153          -  333.99767      -     -    0s
     0     0  348.78288    0  133          -  348.78288      -     -    0s
     0     0  348.87968    0  133          -  348.87968      -     -    0s
     0     0  354.55956    0  142          -  354.55956      -     -    0s
     0     0  354.56602    0  135          -  354.56602      -     -    0s
     0     0  355.33906    0  144          -  355.33906      -     -    0s
     0     0  355.38635    0  143          -  355.38635      -     -    0s
     0     0  355.41644    0  146          -  355.41644      -     -    0s
     0     0  356.15053    0  151          -  356.15053      -     -    0s
     0     0  356.23839    0  146          -  356.23839      -     -    0s
     0     0  356.24102    0  148          -  356.24102      -     -    0s
     0     0  356.24228    0  147          -  356.24228      -     -    0s
     0     0  357.49985    0   39          -  357.49985      -     -    0s
     0     0  357.54234    0   39          -  357.54234      -     -    0s
     0     0  360.28149    0  135          -  360.28149      -     -    0s
     0     0  360.62338    0  135          -  360.62338      -     -    0s
     0     0  360.65466    0  144          -  360.65466      -     -    0s
     0     0  360.92254    0  145          -  360.92254      -     -    0s
     0     0  360.94244    0  145          -  360.94244      -     -    0s
     0     0  361.09686    0  110          -  361.09686      -     -    0s
     0     0  361.09686    0  110          -  361.09686      -     -    0s
     0     0  361.09686    0  110          -  361.09686      -     -    0s
     0     0  361.14723    0  110          -  361.14723      -     -    0s
     0     0  361.14723    0  110          -  361.14723      -     -    0s
     0     0  361.15551    0  110          -  361.15551      -     -    0s
     0     0  361.15551    0  110          -  361.15551      -     -    0s
     0     2  361.15551    0  110          -  361.15551      -     -    0s
*   74    56              22     563.9581316  364.94331  35.3%  27.1    0s
*   81    57              26     558.1085177  364.94331  34.6%  25.3    0s
*   84    56              27     557.0385785  364.94331  34.5%  24.6    0s
*  114    68              21     500.8477402  365.03382  27.1%  23.6    0s
*  144    87              23     480.1483283  365.18181  23.9%  23.3    0s
*  208   118              26     473.8969974  366.18946  22.7%  21.4    0s
*  334   126              14     420.7527751  367.29643  12.7%  20.7    1s
*  709   196              16     415.4016137  372.35876  10.4%  21.8    1s
*  743   182              26     411.7982271  372.97864  9.43%  21.9    1s

Cutting planes:
  Learned: 68
  Gomory: 1
  Cover: 68
  Implied bound: 55
  Clique: 34
  MIR: 46
  Inf proof: 10
  Zero half: 21
  RLT: 13
  Relax-and-lift: 34
  BQP: 11

Explored 1528 nodes (38787 simplex iterations) in 3.34 seconds (1.61 work units)
Thread count was 1 (of 16 available processors)

Solution count 9: 411.798 415.402 420.753 ... 563.958

Optimal solution found (tolerance 1.00e-04)
Best objective 4.117982271427e+02, best bound 4.117982271427e+02, gap 0.0000%

¡Reporte modelo Heuristics = 0 I1!
Tiempo de ejecución: 3.35
Valor objetivo: 411.79822714269534
Gap final: 0.0

In [18]:
modelo_heuristics_I2 = optimizar_modelo_heuristics(datos_2)
reporte_modelo(modelo_heuristics_I2, "modelo Heuristics = 0", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter Heuristics to value 0
¡Optimizando modelo con heuristics = 0!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Heuristics  0
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.08s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)

Root relaxation: objective 5.394012e+02, 540 iterations, 0.02 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  103          -  539.40121      -     -    0s
     0     0  547.80610    0  173          -  547.80610      -     -    0s
     0     0  587.57156    0  161          -  587.57156      -     -    0s
     0     0  591.01636    0   96          -  591.01636      -     -    0s
     0     0  591.24772    0   82          -  591.24772      -     -    0s
     0     0  598.99590    0  112          -  598.99590      -     -    0s
     0     0  600.76258    0  159          -  600.76258      -     -    0s
     0     0  600.79084    0  179          -  600.79084      -     -    0s
     0     0  600.80480    0  198          -  600.80480      -     -    0s
     0     0  608.78711    0  234          -  608.78711      -     -    0s
     0     0  609.22028    0  156          -  609.22028      -     -    0s
     0     0  609.30100    0  217          -  609.30100      -     -    0s
     0     0  609.36353    0  206          -  609.36353      -     -    0s
     0     0  609.37391    0  173          -  609.37391      -     -    0s
     0     0  611.18715    0  226          -  611.18715      -     -    0s
     0     0  611.72083    0  196          -  611.72083      -     -    0s
     0     0  611.86859    0  221          -  611.86859      -     -    0s
     0     0  611.94839    0  170          -  611.94839      -     -    0s
     0     0  611.94839    0  141          -  611.94839      -     -    0s
     0     0  612.49640    0  175          -  612.49640      -     -    0s
     0     0  612.50680    0  180          -  612.50680      -     -    0s
     0     0  612.50680    0  183          -  612.50680      -     -    0s
     0     0  612.69840    0  183          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  141          -  612.69840      -     -    0s
     0     2  612.75339    0  138          -  612.75339      -     -    0s
   659   477  634.52004   12  165          -  634.52004      -  26.6    5s
*  917   533              41     788.2243867  638.39315  19.0%  36.7    7s
*  928   503              47     784.3377100  638.39315  18.6%  36.6    7s
*  931   477              48     781.2327001  638.39315  18.3%  36.5    7s
  1166   542  683.13127   17  128  781.23270  646.28501  17.3%  40.8   10s
* 1801   727              48     779.4129241  657.54439  15.6%  39.9   13s
  2180   912  715.29195   28   93  779.41292  665.87806  14.6%  40.8   15s
  3311  1376 infeasible   32       779.41292  675.27412  13.4%  40.7   20s
  4520  1849  750.33496   27  120  779.41292  683.24154  12.3%  40.0   25s
  5750  2359  737.52724   26   70  779.41292  687.64648  11.8%  39.3   30s
  7139  2846  766.27127   23  127  779.41292  691.99295  11.2%  38.8   35s
  8532  3281  759.38961   29  126  779.41292  696.87016  10.6%  38.2   40s
* 8674  3316              40     779.1682534  697.76941  10.4%  38.2   40s
 10101  3680  732.64410   22  111  779.16825  702.82712  9.80%  37.8   45s
 10203  3713  770.34378   27  141  779.16825  703.29642  9.74%  37.8   53s
 10216  3722  728.14161   27  259  779.16825  703.29642  9.74%  37.7   55s
 10233  3733  710.77405   28  289  779.16825  703.29642  9.74%  37.7   60s
 10252  3746  739.76193   30  307  779.16825  703.29642  9.74%  37.6   65s
 10262  3752  743.69880   30  313  779.16825  703.29642  9.74%  37.6   70s
 10290  3771  720.38373   24  336  779.16825  703.29642  9.74%  37.5   75s
 10419  3826  750.26735   34   68  779.16825  703.29642  9.74%  38.8   80s
 10799  3889  757.22048   35  123  779.16825  703.29642  9.74%  39.6   85s
 11281  3883  730.51458   28  117  779.16825  703.29642  9.74%  40.5   90s
 12208  3867  710.98851   26  159  779.16825  703.29642  9.74%  40.9   95s
*13459  3613              46     777.1647195  709.77444  8.67%  40.6   99s
 13482  3606  741.82572   32   85  777.16472  709.95973  8.65%  40.6  100s
*14173  3351              42     775.3367876  712.94661  8.05%  40.4  102s
 14830  3254     cutoff   40       775.33679  716.99603  7.52%  40.2  105s
 16294  2936  728.12037   28  139  775.33679  724.32541  6.58%  39.6  110s
 17876  2556  735.39236   30  114  775.33679  730.46450  5.79%  39.2  115s
*18303  2214              39     769.2419314  732.12605  4.82%  39.0  116s
 19670  1679  754.56348   36  129  769.24193  737.59854  4.11%  38.4  120s
 21504  1390  765.68881   39   84  769.24193  744.80272  3.18%  37.6  125s
 23586   810  757.28714   39  125  769.24193  754.08473  1.97%  36.8  130s

Cutting planes:
  Learned: 26
  Gomory: 1
  Cover: 156
  Implied bound: 99
  Projected implied bound: 29
  Clique: 48
  MIR: 43
  Mixing: 7
  StrongCG: 3
  Flow cover: 163
  GUB cover: 16
  Inf proof: 10
  Zero half: 98
  RLT: 4
  Relax-and-lift: 10
  BQP: 5

Explored 24834 nodes (892766 simplex iterations) in 132.55 seconds (80.75 work units)
Thread count was 1 (of 16 available processors)

Solution count 8: 769.242 775.337 777.165 ... 788.224

Optimal solution found (tolerance 1.00e-04)
Best objective 7.692419314269e+02, best bound 7.691652927140e+02, gap 0.0100%

¡Reporte modelo Heuristics = 0 I2!
Tiempo de ejecución: 132.55
Valor objetivo: 769.2419314269123
Gap final: 9.962888111753628e-05

### Modelo tuneado

In [19]:
modelo_tuneado_I1 = optimizar_modelo_tuneado(datos_1, "I1")
reporte_modelo(modelo_tuneado_I1, "modelo tuneado", "I1")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter TuneTimeLimit to value 3600
¡Optimizando parametros!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1
TuneTimeLimit  3600

Start tuning.
Tune 34 parameters.

Solving model using baseline parameter set with TimeLimit=600s

Total tuning time limit is 3600s
-------------------------------------------------------------------------------

Testing candidate parameter set 1...

	Threads 1 (fixed)

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... MIP gap 0.01%
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... MIP gap 0.01%
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... MIP gap 0.01%

Summary candidate parameter set 1
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     3.94s    2.48s    3.86s    3.42s     0.67    3.94s

-------------------------------------------------------------------------------
Begin tuning (baseline mean runtime 3.42s)...
-------------------------------------------------------------------------------

Testing candidate parameter set 2...

	Threads 1 (fixed)
	VarBranch 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 3.56s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.22s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 3.69s

Summary candidate parameter set 2
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     3.56s    2.22s    3.69s    3.16s     0.66    3.69s

Improvement found:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  improved: mean runtime 3.16s (parameter set 2, 1 non-defaults)
Total elapsed tuning time 20s (3580s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 3...

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 5.25s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 5.08s

Summary candidate parameter set 3 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     5.25s    5.08s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 3.16s (parameter set 2, 1 non-defaults)
Total elapsed tuning time 30s (3570s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 4...

	Threads 1 (fixed)
	VarBranch 0
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.02s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.92s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.14s

Summary candidate parameter set 4
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.02s    1.92s    2.14s    2.03s     0.09    2.14s

Improvement found:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  improved: mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 36s (3564s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 5...

	Threads 1 (fixed)
	Method 1
	VarBranch 0
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.03s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.90s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.11s

Summary candidate parameter set 5
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.03s    1.90s    2.11s    2.01s     0.09    2.11s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 42s (3558s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 6...

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.93s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 3.20s

Summary candidate parameter set 6 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.93s    3.20s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 48s (3552s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 7...

	Threads 1 (fixed)
	VarBranch 0
	CutPasses 3
	PreDepRow 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.03s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.92s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.06s

Summary candidate parameter set 7
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.03s    1.92s    2.06s    2.00s     0.06    2.06s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 54s (3546s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 8...

	Threads 1 (fixed)
	VarBranch 3
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 7.00s (limit)

Summary candidate parameter set 8 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    7.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 62s (3539s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 9...

	Threads 1 (fixed)
	NoRelHeurTime 3
	VarBranch 0
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 7.00s (limit)

Summary candidate parameter set 9 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    7.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.03s (parameter set 4, 2 non-defaults)
Total elapsed tuning time 69s (3531s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 10...

	Threads 1 (fixed)
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 1.97s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.87s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.16s

Summary candidate parameter set 10
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     1.97s    1.87s    2.16s    2.00s     0.12    2.16s

Improvement found:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  improved: mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 75s (3525s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 11...

	Threads 1 (fixed)
	CutPasses 3
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.12s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.64s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 3.42s

Summary candidate parameter set 11
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.12s    1.64s    3.42s    2.39s     0.75    3.42s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 82s (3518s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 12...

	Threads 1 (fixed)
	NoRelHeurTime 1
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 5.41s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 3.90s

Summary candidate parameter set 12 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     5.41s    3.90s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 91s (3509s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 13...

	Threads 1 (fixed)
	Heuristics 0.5
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.39s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.82s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 1.94s

Summary candidate parameter set 13
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.39s    2.82s    1.94s    2.38s     0.36    2.82s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 98s (3502s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 14...

	Threads 1 (fixed)
	Cuts 3
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 4.97s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 4.86s

Summary candidate parameter set 14 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     4.97s    4.86s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 108s (3492s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 15...

	Threads 1 (fixed)
	NoRelHeurTime 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.58s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 3.92s

Summary candidate parameter set 15 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.58s    3.92s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 115s (3485s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 16...

	Threads 1 (fixed)
	MIPFocus 2

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 5.44s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 4.97s

Summary candidate parameter set 16 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     5.44s    4.97s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 2.00s (parameter set 10, 1 non-defaults)
Total elapsed tuning time 125s (3475s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 17...

	Threads 1 (fixed)
	Heuristics 0.001
	CutPasses 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 1.93s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.73s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.02s

Summary candidate parameter set 17
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     1.93s    1.73s    2.02s    1.89s     0.12    2.02s

Improvement found:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  improved: mean runtime 1.89s (parameter set 17, 2 non-defaults)
Total elapsed tuning time 131s (3469s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 18...

	Threads 1 (fixed)
	Heuristics 0.001
	CutPasses 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 1.95s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.60s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 1.91s

Summary candidate parameter set 18
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     1.95s    1.60s    1.91s    1.82s     0.15    1.95s

Improvement found:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  improved: mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 136s (3464s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 19...

	Threads 1 (fixed)
	Heuristics 0.001
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 3.63s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.16s

Summary candidate parameter set 19 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     3.63s    2.16s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 142s (3458s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 20...

	Threads 1 (fixed)
	CutPasses 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.09s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.86s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.33s

Summary candidate parameter set 20
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.09s    1.86s    2.33s    2.09s     0.19    2.33s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 148s (3452s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 21...

	Threads 1 (fixed)
	Heuristics 0.001
	CutPasses 3
	AggFill 100
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 7.00s (limit)

Summary candidate parameter set 21 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    7.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 155s (3445s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 22...

	Threads 1 (fixed)
	Heuristics 0.001
	RINS 2500
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.33s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.03s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 2.34s

Summary candidate parameter set 22
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.33s    2.03s    2.34s    2.23s     0.15    2.34s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 162s (3438s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 23...

	Threads 1 (fixed)
	DegenMoves 0
	CutPasses 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.56s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.93s

Summary candidate parameter set 23 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.56s    2.93s        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 168s (3432s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 24...

	Threads 1 (fixed)
	Heuristics 0.001
	Symmetry 2
	CutPasses 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 1.89s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 1.67s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 1.91s

Summary candidate parameter set 24
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     1.89s    1.67s    1.91s    1.83s     0.11    1.91s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 173s (3427s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 25...

	Threads 1 (fixed)
	BranchDir -1
	Heuristics 0.001
	CutPasses 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 2.96s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 2.18s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 3.71s

Summary candidate parameter set 25
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     2.96s    2.18s    3.71s    2.95s     0.62    3.71s

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 182s (3418s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 26...

	Threads 1 (fixed)
	Heuristics 0.001
	CutPasses 3
	NumericFocus 3
	Presolve 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 6.12s

Summary candidate parameter set 26 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL     6.12s        -        -        -        -        -

Progress so far:
  baseline: mean runtime 3.42s (parameter set 1, 0 non-defaults)
  best:     mean runtime 1.82s (parameter set 18, 3 non-defaults)
Total elapsed tuning time 188s (3412s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 27...

	Threads 1 (fixed)
	NoRelHeurTime 3

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 5.16s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 4.40s

Summary candidate parameter set 27 (discarded)

In [20]:
modelo_tuneado_I2 = optimizar_modelo_tuneado(datos_2, "I2")
reporte_modelo(modelo_tuneado_I2, "modelo tuneado", "I2")

Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Set parameter TuneTimeLimit to value 3600
¡Optimizando parametros!

Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
TimeLimit  600
Threads  1
TuneTimeLimit  3600

Start tuning.
Tune 34 parameters.

Solving model using baseline parameter set with TimeLimit=600s

Total tuning time limit is 3600s
-------------------------------------------------------------------------------

Testing candidate parameter set 1...

	Threads 1 (fixed)

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... MIP gap 0.01%
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... MIP gap 0.01%
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... MIP gap 0.01%

Summary candidate parameter set 1
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   224.36s  106.13s  156.42s  162.30s    48.45  224.36s

-------------------------------------------------------------------------------
Begin tuning (baseline mean runtime 162.30s)...
-------------------------------------------------------------------------------

Testing candidate parameter set 2...

	Threads 1 (fixed)
	VarBranch 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 145.63s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 55.93s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 83.05s

Summary candidate parameter set 2
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   145.63s   55.93s   83.05s   94.87s    37.56  145.63s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 94.87s (parameter set 2, 1 non-defaults)
Total elapsed tuning time 772s (2828s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 3...

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 109.50s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 96.70s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 71.16s

Summary candidate parameter set 3
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   109.50s   96.70s   71.16s   92.45s    15.94  109.50s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 92.45s (parameter set 3, 2 non-defaults)
Total elapsed tuning time 1049s (2551s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 4...

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 63.80s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 77.74s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 113.40s

Summary candidate parameter set 4
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    63.80s   77.74s  113.40s   84.98s    20.89  113.40s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 1304s (2296s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 5...

	Threads 1 (fixed)
	Method 1
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 63.11s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 86.58s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 125.60s

Summary candidate parameter set 5
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    63.11s   86.58s  125.60s   91.76s    25.78  125.60s

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 1579s (2021s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 6...

	Threads 1 (fixed)
	MIPFocus 2
	NoRelHeurTime 146
	VarBranch 0
	GomoryPasses 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 146.00s (limit)

Summary candidate parameter set 6 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL  146.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 1725s (1875s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 7...

	Threads 1 (fixed)
	MIPFocus 2
	Symmetry 2
	VarBranch 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 110.23s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 97.70s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 74.08s

Summary candidate parameter set 7
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   110.23s   97.70s   74.08s   94.00s    14.99  110.23s

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 2007s (1593s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 8...

	Threads 1 (fixed)
	MIPFocus 2
	GomoryPasses 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 68.37s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 82.97s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 122.27s

Summary candidate parameter set 8
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    68.37s   82.97s  122.27s   91.20s    22.76  122.27s

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 2281s (1319s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 9...

	Threads 1 (fixed)
	SimplexPricing 2
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 78.46s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 39.85s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 140.74s

Summary candidate parameter set 9
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    78.46s   39.85s  140.74s   86.35s    41.56  140.74s

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 84.98s (parameter set 4, 3 non-defaults)
Total elapsed tuning time 2540s (1060s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 10...

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 71.42s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 62.66s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 94.66s

Summary candidate parameter set 10
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    71.42s   62.66s   94.66s   76.25s    13.50   94.66s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 76.25s (parameter set 10, 4 non-defaults)
Total elapsed tuning time 2769s (831s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 11...

	Threads 1 (fixed)
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 71.50s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 65.45s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 74.46s

Summary candidate parameter set 11
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    71.50s   65.45s   74.46s   70.47s     3.75   74.46s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 70.47s (parameter set 11, 5 non-defaults)
Total elapsed tuning time 2980s (620s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 12...

	Threads 1 (fixed)
	MIPFocus 2
	RINS 100
	VarBranch 0
	CutPasses 3
	GomoryPasses 1
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 98.00s (limit)

Summary candidate parameter set 12 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   98.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 70.47s (parameter set 11, 5 non-defaults)
Total elapsed tuning time 3078s (522s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 13...

	Threads 1 (fixed)
	Disconnected 1
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 67.19s
Solving ConVRP_SLA_Reducido (Min) with random seed #2 ... runtime 61.65s
Solving ConVRP_SLA_Reducido (Min) with random seed #3 ... runtime 72.48s

Summary candidate parameter set 13
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    67.19s   61.65s   72.48s   67.11s     4.42   72.48s

Improvement found:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  improved: mean runtime 67.11s (parameter set 13, 6 non-defaults)
Total elapsed tuning time 3280s (320s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 14...

	Threads 1 (fixed)
	Disconnected 1
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0
	PreSparsify 1

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 95.00s (limit)

Summary candidate parameter set 14 (discarded)
 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   95.00s*        -        -        -        -        -

Progress so far:
  baseline: mean runtime 162.30s (parameter set 1, 0 non-defaults)
  best:     mean runtime 67.11s (parameter set 13, 6 non-defaults)
Total elapsed tuning time 3375s (225s remaining, 1 running jobs)

-------------------------------------------------------------------------------

Testing candidate parameter set 15...

	Threads 1 (fixed)
	NormAdjust 0
	Disconnected 1
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

Solving ConVRP_SLA_Reducido (Min) with random seed #1 ... runtime 48.50s


Tune time limit reached

-------------------------------------------------------------------------------

Tested 14 parameter sets in 3423.09s
Total optimization run time for up to 1 concurrent runs: 3422.79s

Baseline parameter set: mean runtime 162.30s

	Threads 1 (fixed)

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   224.36s  106.13s  156.42s  162.30s    48.45  224.36s

Improved parameter set 1 (mean runtime 67.11s):

	Threads 1 (fixed)
	Disconnected 1
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    67.19s   61.65s   72.48s   67.11s     4.42   72.48s

Improved parameter set 2 (mean runtime 70.47s):

	Threads 1 (fixed)
	MIPFocus 2
	RINS 100
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    71.50s   65.45s   74.46s   70.47s     3.75   74.46s

Improved parameter set 3 (mean runtime 76.25s):

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1
	Aggregate 0

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    71.42s   62.66s   94.66s   76.25s    13.50   94.66s

Improved parameter set 4 (mean runtime 84.98s):

	Threads 1 (fixed)
	MIPFocus 2
	VarBranch 0
	GomoryPasses 1

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    63.80s   77.74s  113.40s   84.98s    20.89  113.40s

Improved parameter set 5 (mean runtime 91.20s):

	Threads 1 (fixed)
	MIPFocus 2
	GomoryPasses 1

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL    68.37s   82.97s  122.27s   91.20s    22.76  122.27s

Improved parameter set 6 (mean runtime 94.87s):

	Threads 1 (fixed)
	VarBranch 0

 # Name              0        1        2      Avg  Std Dev      Max
 0 ConVRP_SL   145.63s   55.93s   83.05s   94.87s    37.56  145.63s

¡Optimizando modelo con parametros tuneados!
Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (win64 - Windows 11+.0 (26300.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 8 physical cores, 16 logical processors, using up to 1 threads

Non-default parameters:
Threads  1

Optimize a model with 1506 rows, 1360 columns and 6669 nonzeros (Min)
Model fingerprint: 0xc86c9a53
Model has 1260 linear objective coefficients
Variable types: 46 continuous, 1314 integer (1314 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve removed 312 rows and 147 columns
Presolve time: 0.02s
Presolved: 1194 rows, 1213 columns, 5331 nonzeros
Variable types: 34 continuous, 1179 integer (1179 binary)

Root relaxation: objective 5.394012e+02, 540 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  539.40121    0  103          -  539.40121      -     -    0s
     0     0  547.80610    0  173          -  547.80610      -     -    0s
     0     0  587.57156    0  161          -  587.57156      -     -    0s
     0     0  591.01636    0   96          -  591.01636      -     -    0s
     0     0  591.24772    0   82          -  591.24772      -     -    0s
     0     0  598.99590    0  112          -  598.99590      -     -    0s
     0     0  600.76258    0  159          -  600.76258      -     -    0s
     0     0  600.79084    0  179          -  600.79084      -     -    0s
     0     0  600.80480    0  198          -  600.80480      -     -    0s
     0     0  608.78711    0  234          -  608.78711      -     -    0s
     0     0  609.22028    0  156          -  609.22028      -     -    0s
     0     0  609.30100    0  217          -  609.30100      -     -    0s
     0     0  609.36353    0  206          -  609.36353      -     -    0s
     0     0  609.37391    0  173          -  609.37391      -     -    0s
     0     0  611.18715    0  226          -  611.18715      -     -    0s
     0     0  611.72083    0  196          -  611.72083      -     -    0s
     0     0  611.86859    0  221          -  611.86859      -     -    0s
     0     0  611.94839    0  170          -  611.94839      -     -    0s
     0     0  611.94839    0  141          -  611.94839      -     -    0s
     0     0  612.49640    0  175          -  612.49640      -     -    0s
     0     0  612.50680    0  180          -  612.50680      -     -    0s
     0     0  612.50680    0  183          -  612.50680      -     -    0s
     0     0  612.69840    0  183          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  144          -  612.69840      -     -    0s
     0     0  612.69840    0  140          -  612.69840      -     -    0s
     0     2  612.88549    0  138          -  612.88549      -     -    0s
H  637   451                     936.5462785  635.33787  32.2%  20.5    2s
H  637   428                     925.4757949  635.33787  31.4%  20.5    2s
H  648   414                     844.5315761  636.60671  24.6%  26.5    3s
H  648   392                     841.0582862  636.60671  24.3%  26.5    3s
H  649   372                     840.7017084  636.60671  24.3%  26.7    3s
H  649   353                     840.1164889  636.60671  24.2%  26.7    3s
H  649   334                     839.3136417  636.60671  24.2%  26.7    3s
H  756   363                     830.1588823  646.32366  22.1%  30.7    3s
H  756   346                     827.8976697  646.32366  21.9%  30.7    4s
   997   411  675.97970   23  154  827.89767  653.27315  21.1%  37.5    5s
H 1138   403                     794.0304202  656.75627  17.3%  39.5    5s
H 1848   670                     793.6310751  666.22962  16.1%  42.5    7s
H 1848   640                     782.3070372  666.22962  14.8%  42.5    7s
H 2048   745                     780.4791053  668.88098  14.3%  43.1    8s
  2723  1073  769.52362   30   77  780.47911  675.76444  13.4%  42.3   10s
H 3050  1242                     779.1096739  677.57178  13.0%  41.5   10s
H 3050  1238                     778.4295960  677.57178  13.0%  41.5   10s
H 3050  1227                     775.2900138  677.57178  12.6%  41.5   10s
  5163  2141  737.04254   31   35  775.29001  687.32431  11.3%  38.7   15s
  7773  3089  714.72167   22  100  775.29001  695.04151  10.4%  36.8   20s
 10203  3981  752.46230   34  140  775.29001  700.48557  9.65%  34.8   27s
 10227  3997  701.84616   28  314  775.29001  700.48557  9.65%  34.7   30s
 10258  4018  746.25769   32  304  775.29001  700.48557  9.65%  34.6   35s
 10306  4050  722.87139   25  316  775.29001  700.48557  9.65%  34.5   40s
 10802  4171  700.48557   32  169  775.29001  700.48557  9.65%  36.9   45s
 12024  4309  721.91385   42   80  775.29001  700.48557  9.65%  37.3   50s
 14727  4506  729.98274   39  112  775.29001  704.07549  9.19%  36.6   55s
 18214  4397  758.69761   33  171  775.29001  714.64534  7.82%  35.3   60s
 22462  4143  732.34274   43   71  775.29001  721.32539  6.96%  33.7   65s
 26349  4882  744.94352   41   46  775.29001  726.63784  6.28%  32.9   70s
 30439  5526  744.74844   39  100  775.29001  731.01140  5.71%  32.1   75s
 34958  5952  758.84207   42   64  775.29001  735.31940  5.16%  31.4   80s
 39422  6227  748.76769   36  155  775.29001  738.65835  4.72%  30.7   85s
*42739  6080              54     769.2419314  741.06847  3.66%  30.3   88s
 43826  5998  757.48476   49   81  769.24193  742.14271  3.52%  30.1   90s
 48093  5462  748.16182   42   62  769.24193  746.44546  2.96%  29.7   95s
 53071  4308     cutoff   46       769.24193  751.54307  2.30%  29.1  100s
 58485  1757  764.07284   45   58  769.24193  759.68212  1.24%  28.5  105s

Cutting planes:
  Learned: 24
  Gomory: 2
  Cover: 263
  Implied bound: 126
  Projected implied bound: 22
  Clique: 50
  MIR: 41
  StrongCG: 5
  Flow cover: 179
  GUB cover: 12
  Inf proof: 18
  Zero half: 109
  RLT: 7
  Relax-and-lift: 15
  BQP: 5


# Comparativa de modelos

In [21]:
modelos_I1 = [modelo_base_I1, modelo_cuts_I1, modelo_presolve_I1, modelo_mipfocus1_I1, modelo_mipfocus3_I1, modelo_heuristics_I1, modelo_tuneado_I1]

nombres = ["Baseline", "Cuts=0", "Presolve=0", "MIPF=1", "MIPF=3", "Heuristics=0","Tuneado"]

comparacion_modelos(modelos_I1, nombres, "I1")

=== Comparativa de modelos I1 ===

         Modelo  Tiempo  Valor Objetivo  Gap Final
0      Baseline   2.468      411.798227        0.0
1        Cuts=0   4.473      411.798227        0.0
2    Presolve=0  14.293      411.798227        0.0
3        MIPF=1  10.529      411.798227        0.0
4        MIPF=3   8.900      411.798227        0.0
5  Heuristics=0   3.346      411.798227        0.0
6       Tuneado   3.702      411.798227        0.0

In [28]:
modelos_I2 = [modelo_base_I2, modelo_cuts_I2, modelo_presolve_I2, modelo_mipfocus1_I2, modelo_mipfocus3_I2, modelo_heuristics_I2, modelo_tuneado_I2]

comparacion_modelos(modelos_I2, nombres, "I2")

=== Comparativa de modelos I2 ===

         Modelo   Tiempo  Valor Objetivo  Gap Final
0      Baseline  201.689      769.241931   0.000089
1        Cuts=0  600.006      769.241931   0.066428
2    Presolve=0  600.022      769.241931   0.042903
3        MIPF=1  462.658      769.241931   0.000087
4        MIPF=3  223.766      769.241931   0.000089
5  Heuristics=0  132.552      769.241931   0.000100
6       Tuneado  106.450      769.241931   0.000089

#  Analisis de sensibilidad

In [25]:
res_sens_I1 = analisis_sensibilidad_capacidad(modelo_tuneado_I1, "I1")

Set parameter Presolve to value 0
Set parameter Method to value 1
Set parameter Threads to value 1
=== Sensibilidad de Q, instancia I1 ===
Objetivo MIP: 411.7982 | Objetivo LP fijado: 411.7982
Restricciones de capacidad: 9 | activas: 0
Carga máxima observada: 130.00 (Q = 200.00)
Filas con precio sombra distinto de 0: 0

,Restricción,Q (RHS),Carga,Holgura,Activa,Precio sombra (Pi),SARHSLow,SARHSUp
2,Capacidad (R1421),200.0,130.0,70.0,False,0.0,130.0,inf
0,Capacidad (R1419),200.0,120.0,80.0,False,0.0,120.0,inf
1,Capacidad (R1420),200.0,120.0,80.0,False,0.0,120.0,inf
3,Capacidad (R1422),200.0,70.0,130.0,False,0.0,70.0,inf
4,Capacidad (R1423),200.0,70.0,130.0,False,0.0,70.0,inf
5,Capacidad (R1424),200.0,60.0,140.0,False,0.0,60.0,inf
6,Capacidad (R1425),200.0,0.0,200.0,False,0.0,0.0,inf
7,Capacidad (R1426),200.0,0.0,200.0,False,0.0,0.0,inf
8,Capacidad (R1427),200.0,0.0,200.0,False,0.0,0.0,inf

In [26]:
res_sens_I2 = analisis_sensibilidad_capacidad(modelo_tuneado_I2, "I2")

Set parameter Presolve to value 0
Set parameter Method to value 1
Set parameter Threads to value 1
=== Sensibilidad de Q, instancia I2 ===
Objetivo MIP: 769.2419 | Objetivo LP fijado: 769.2419
Restricciones de capacidad: 9 | activas: 0
Carga máxima observada: 89.00 (Q = 200.00)
Filas con precio sombra distinto de 0: 0

,Restricción,Q (RHS),Carga,Holgura,Activa,Precio sombra (Pi),SARHSLow,SARHSUp
8,Capacidad (R1505),200.0,89.0,111.0,False,0.0,89.0,inf
4,Capacidad (R1501),200.0,82.0,118.0,False,0.0,82.0,inf
3,Capacidad (R1500),200.0,75.0,125.0,False,0.0,75.0,inf
6,Capacidad (R1503),200.0,59.0,141.0,False,0.0,59.0,inf
7,Capacidad (R1504),200.0,57.0,143.0,False,0.0,57.0,inf
5,Capacidad (R1502),200.0,42.0,158.0,False,0.0,42.0,inf
0,Capacidad (R1497),200.0,26.0,174.0,False,0.0,26.0,inf
1,Capacidad (R1498),200.0,26.0,174.0,False,0.0,26.0,inf
2,Capacidad (R1499),200.0,0.0,200.0,False,0.0,0.0,inf